#!/bin/sh

##H Usage: manage ACTION [SECURITY-STRING]
##H
##H Available actions:
##H   help        show this help
##H   status      show current service's status
##H   configtest  check server configuration
##H   restart     (re)start the service
##H   start       (re)start the service
##H   graceful    restart the service gracefully
##H   stop        stop the service
##H
##H For more details please refer to operations page:
##H   https://twiki.cern.ch/twiki/bin/view/CMS/ServiceApache

ME=$(basename $(dirname $0))
TOP=$(cd $(dirname $0)/../../.. && pwd)
ROOT=$(cd $(dirname $0)/../.. && pwd)
STATEDIR=$TOP/state/$ME

# x509-scitokens-issuer settings
export X509_SCITOKENS_ISSUER_CONFIG=$STATEDIR/x509_scitokens_issuer/x509_scitokens_issuer_app.json
export X509_SCITOKENS_ISSUER_INSTANCE_PATH=$STATEDIR/x509_scitokens_issuer

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$STATEDIR/libs:/usr/lib64
. $ROOT/apps/$ME/etc/profile.d/init.sh

# Detect if we have system httpd daemon
if [ -f /usr/sbin/apachectl ]; then
    sudo /usr/sbin/apachectl stop
fi

case ${1:-status} in
  status | graceful | stop | configtest )
    $STATEDIR/etc/httpd $1
    ;;

  start | restart )
    echo "stopping httpd service ..."
    $STATEDIR/etc/httpd stop
    ipids=`ipcs -s | awk '/apache|frontend/ {print $2}'`
    if [ -n "$ipids" ]; then
        echo "for i in $ipids; do (sudo ipcrm -s $i); done"
        for i in `ipcs -s | awk '/apache/ {print $2}'`; do (sudo ipcrm -s $i); done
    fi
    echo "restarting httpd service ..."
    $STATEDIR/etc/httpd restart
    ;;

  help )
    perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
    ;;

  * )
    echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
    exit 1
    ;;
esac