#! /bin/bash

case $(id -un) in cmsweb ) echo "ERROR: please use another account" 1>&2; exit 1;; esac

#######################################################
# Phedex-WEB management script
# Author: Ignas Butenas, contact if needed by email: ignas.butenas@cern.ch
#######################################################
# Setting the basic and common variables.
# Make sure that these are up to date.
# If need a new variable, it must be defined here.
# Use export if you really need this!
#######################################################

ME=$(basename $(dirname $0))
TOP=$(cd $(dirname $0)/../../.. && pwd)
ROOT=$(cd $(dirname $0)/../.. && pwd)
CFGDIR=$(dirname $0)
LOGDIR=$TOP/logs/$ME
STATEDIR=$TOP/state/$ME
SERVICE_TITLE="PhEDEx"
TWIKI_PAGE="https://twiki.cern.ch/twiki/bin/view/CMS/PhedexOperationsWebSite#WebStart"
PHEDEX_PATTERN="/httpd -f $STATEDIR/server.conf"
GRAPHS_PATTERN="phedex-web.*[/]graphs_website_prod.xml"
for app in PHEDEX-{datasvc,web,webapp}; do
  . $ROOT/apps/$app/etc/profile.d/init.sh
done
PHEDEX_GRAPHS_ROOT=$PHEDEX_WEB_ROOT/Documentation/WebSite/PlotConfig
GLOBAL_GRAPHS_ROOT=$WEBTOOLS_ROOT/lib/python2.6/site-packages/Tools/GraphTool
export PYTHONPATH=$PHEDEX_GRAPHS_ROOT/src:$GLOBAL_GRAPHS_ROOT/src:$PYTHONPATH
export GLOBAL_GRAPHS_ROOT # for the .xml files
export MPLCONFIGDIR=$STATEDIR

#######################################################
# Function for the main actions.
# If using the variable here, need to define it in the
# top part of the script, to keep them in one place.
#######################################################
# Function to start the service conditionally on crond restart
function sysboot {
  if [ $(pgrep -u $(id -u) -f "$PHEDEX_PATTERN" | wc -l) = 0 ] ||
     [ $(pgrep -u $(id -u) -f "$GRAPHS_PATTERN" | wc -l) = 0 ]; then
    start
  fi
}

# Start the graphs service
function start_graphs {
  python -u $PHEDEX_GRAPHS_ROOT/tools/phedex-web.py $STATEDIR/etc/graphs_website_prod.xml \
    </dev/null 2>&1 | rotatelogs $LOGDIR/graphs-%Y%m%d.log 86400 >/dev/null 2>&1 &
}

# Stop the graphs service
function kill_graphs {
  for PID in $(pgrep -u $(id -u) -f "$GRAPHS_PATTERN" | sort -rn); do
    PSLINE=$(ps -o pid=,bsdstart=,args= $PID |
             perl -n -e 'print join(" ", (split)[0..6])')
    echo "Stopping $PID ($PSLINE):"
    kill -9 $PID
  done
}

# Function which is used to start the service
function start {
  cd $STATEDIR
  echo "Starting the $SERVICE_TITLE"
  $STATEDIR/etc/httpd start </dev/null 2>&1
  start_graphs
}

# Function which is used to stop the service
function stop {
  echo "Stopping the $SERVICE_TITLE"
  $STATEDIR/etc/httpd stop
  kill_graphs
}

# Function to check the status of the process
function status {
  echo "Checking the $SERVICE_TITLE status..."
  $STATEDIR/etc/httpd status

  GPIDS=$(pgrep -u $(id -u) -f "$GRAPHS_PATTERN" | sort -rn)
  if [ X"$GPIDS" != X ]; then
    echo "PhEDEx graph service is RUNNING, PID: $GPIDS"
  else
    echo "PhEDEx graph service is NOT RUNNING."
  fi
}

# Function to do graceful restart
function graceful {
  echo "Restarting gracefully the $SERVICE_TITLE"
  $STATEDIR/etc/httpd graceful
}

#######################################################
# Function to provide the help for the user
# To edit the help provided, edit lines with the ##H prefix
#######################################################
##H Available actions:
##H   status - show current service's status
##H   start - start the service
##H   stop - stop the service
##H   restart - restart the service
##H   graceful - restart the service gracefully
##H   rgraphs - restart only the graphs service
##H   version - get current version of the service
##H Security string - string needed to perform actions, see twiki page
#######################################################
function help {
  echo "$SERVICE_TITLE management script"
  echo "Usage: $0 status|start|stop|restart|rgraphs|help|version security_string"
  echo "For more details, check the Twiki page: $TWIKI_PAGE"
  perl -ne '/^##H / && do { s/^##H ?//; print }' < $0
}

# Function to check the security string.
function check {
  CHECK=$(echo "$1" | md5sum | awk '{print $1}')
  if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
    echo "$0: cannot complete operation, please check documentation."
    exit 2;
  fi
}

#######################################################
# The engine of the script. The place where the
# script reacts to the actions.
# Params: $1 - action
#         $2 - security string
#######################################################

case $1 in
  sysboot)
    if ps -oargs= $PPID | grep -q -e crond; then
      sysboot
    else
      echo "$0: sysboot is for cron only" 1>&2
      exit 1
    fi ;;
  start | restart)
    check "$2"
    stop
    start
    status
    ;;
  status)
    status
    ;;
  stop)
    check "$2"
    stop
    status
    ;;
  graceful)
    check "$2"
    graceful
    status
    ;;
  rgraphs)
    check "$2"
    cd $STATEDIR
    kill_graphs
    start_graphs
    status
    ;;
  help)
    help
    ;;
  version)
    echo "Management script for $SERVICE_TITLE."
    ;;
  * )
    echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
    exit 1 ;;
esac
