#!/bin/sh

##H Usage: manage ACTION [SECURITY-STRING]
##H
##H Available actions:
##H   help              show this help
##H   version           get current version of the service
##H   status            show current service's status
##H   sysboot           start server from crond if not running
##H   restart           (re)start the service
##H   start             (re)start the service
##H   stop              stop the service
##H
##H For more details please refer to operations page:
##H   https://twiki.cern.ch/twiki/bin/view/CMS/ReqMgrSystemDesign
##H [nice, obsolete twiki, leave for reference and example ...]

if [ $(id -un)  = cmsweb ]; then
  echo "ERROR: please use another account" 1>&2
  exit 1
fi

echo_e=-e bsdstart=bsdstart
case $(uname) in
  Darwin )
    md5sum() { md5 -r ${1+"$@"}; }
    echo_e= bsdstart=start
    ;;
esac

ME=$(basename $(dirname $0))
TOP=$(cd $(dirname $0)/../../.. && pwd)
ROOT=$(cd $(dirname $0)/../.. && pwd)
CFGDIR=$(dirname $0)
LOGDIR=$TOP/logs/$ME
STATEDIR=$TOP/state/$ME
CFGFILETR=$CFGDIR/config-transferor.py
CFGFILEMON=$CFGDIR/config-monitor.py
CFGFILEOUT=$CFGDIR/config-output.py
CFGFILERCLEAN=$CFGDIR/config-ruleCleaner.py
LOG_TRANS=ms-transferor
LOG_MON=ms-monitor
LOG_OUT=ms-output
LOG_RCLEAN=ms-rulecleaner
AUTHDIR=$TOP/current/auth/reqmgr2ms
COLOR_OK="\\033[0;32m"
COLOR_WARN="\\033[0;31m"
COLOR_NORMAL="\\033[0;39m"

. $ROOT/apps/$ME/etc/profile.d/init.sh

export WMCORE_USE_RUCIO=false
export PYTHONPATH=$ROOT/auth/$ME:$PYTHONPATH
export WMCORE_ROOT=$REQMGR2MS_ROOT/lib/python*/site-packages
export REQMGR_CACHE_DIR=$STATEDIR
export WMCORE_CACHE_DIR=$STATEDIR
export RUCIO_HOME=$CFGDIR
if [ -e $AUTHDIR/dmwm-service-cert.pem ] && [ -e $AUTHDIR/dmwm-service-key.pem ]; then
  export X509_USER_CERT=$AUTHDIR/dmwm-service-cert.pem
  export X509_USER_KEY=$AUTHDIR/dmwm-service-key.pem
fi


check4db ()
{
python <<EOF
from pymongo import MongoClient, errors
client = MongoClient('127.0.0.1', port=8230)
try:
    client.admin.command('ismaster')
except errors.ConnectionFailure as ex:
    raise ex
EOF
return $?
}


# helper function to wait for MongoDB appearance
# it will incrementally increase waiting time with 20 iterations (~3minute)
wait4db() {
    local counter=0
    # check if mongodb is running
    while [  $counter -lt 20 ]; do
        check4db && break
        let counter=counter+1
        echo "MongoDB is not running, check in $counter sec"
        sleep $counter
    done
    check4db || {
        echo "MongoDB is not running, unable to start MicroServices server"
        exit 1
        }
}


# Start service conditionally on crond restart.
sysboot()
{
  if [ -f $CFGFILETR ]; then
    LD_PRELOAD=$JEMALLOC_ROOT/lib/libjemalloc.so wmc-httpd -v -d $STATEDIR -l "|rotatelogs $LOGDIR/$LOG_TRANS-%Y%m%d-`hostname -s`.log 86400" $CFGFILETR
  fi
  if [ -f $CFGFILEMON ]; then
    LD_PRELOAD=$JEMALLOC_ROOT/lib/libjemalloc.so wmc-httpd -v -d $STATEDIR -l "|rotatelogs $LOGDIR/$LOG_MON-%Y%m%d-`hostname -s`.log 86400" $CFGFILEMON
  fi
  if [ -f $CFGFILEOUT ]; then
    # Check for MongoDB before starting MicroServices:
    wait4db

    LD_PRELOAD=$JEMALLOC_ROOT/lib/libjemalloc.so wmc-httpd -v -d $STATEDIR -l "|rotatelogs $LOGDIR/$LOG_OUT-%Y%m%d-`hostname -s`.log 86400" $CFGFILEOUT
  fi
  if [ -f $CFGFILERCLEAN ]; then
    LD_PRELOAD=$JEMALLOC_ROOT/lib/libjemalloc.so wmc-httpd -v -d $STATEDIR -l "|rotatelogs $LOGDIR/$LOG_RCLEAN-%Y%m%d-`hostname -s`.log 86400" $CFGFILERCLEAN
  fi
}


# Start the service.
start()
{
  echo "starting $ME"
  if [ -f $CFGFILETR ]; then
    LD_PRELOAD=$JEMALLOC_ROOT/lib/libjemalloc.so wmc-httpd -r -d $STATEDIR -l "|rotatelogs $LOGDIR/$LOG_TRANS-%Y%m%d-`hostname -s`.log 86400" $CFGFILETR
  fi
  if [ -f $CFGFILEMON ]; then
    LD_PRELOAD=$JEMALLOC_ROOT/lib/libjemalloc.so wmc-httpd -r -d $STATEDIR -l "|rotatelogs $LOGDIR/$LOG_MON-%Y%m%d-`hostname -s`.log 86400" $CFGFILEMON
  fi
  if [ -f $CFGFILEOUT ]; then
    # Check for MongoDB before starting MicroServices:
    wait4db

    LD_PRELOAD=$JEMALLOC_ROOT/lib/libjemalloc.so wmc-httpd -r -d $STATEDIR -l "|rotatelogs $LOGDIR/$LOG_OUT-%Y%m%d-`hostname -s`.log 86400" $CFGFILEOUT
  fi
  if [ -f $CFGFILERCLEAN ]; then
    LD_PRELOAD=$JEMALLOC_ROOT/lib/libjemalloc.so wmc-httpd -r -d $STATEDIR -l "|rotatelogs $LOGDIR/$LOG_RCLEAN-%Y%m%d-`hostname -s`.log 86400" $CFGFILERCLEAN
  fi
}


# Stop the service.
stop()
{
  echo "stopping $ME"
  if [ -f $CFGFILETR ]; then
    wmc-httpd -k -d $STATEDIR $CFGFILETR
  fi
  if [ -f $CFGFILEMON ]; then
    wmc-httpd -k -d $STATEDIR $CFGFILEMON
  fi
  if [ -f $CFGFILEOUT ]; then
    wmc-httpd -k -d $STATEDIR $CFGFILEOUT
  fi
  if [ -f $CFGFILERCLEAN ]; then
    wmc-httpd -k -d $STATEDIR $CFGFILERCLEAN
  fi
}


# Check if the server is running.
status()
{
  if [ -f $CFGFILETR ]; then
    wmc-httpd -s -d $STATEDIR $CFGFILETR
  fi
  if [ -f $CFGFILEMON ]; then
    wmc-httpd -s -d $STATEDIR $CFGFILEMON
  fi
  if [ -f $CFGFILEOUT ]; then
    wmc-httpd -s -d $STATEDIR $CFGFILEOUT
  fi
  if [ -f $CFGFILERCLEAN ]; then
    wmc-httpd -s -d $STATEDIR $CFGFILERCLEAN
  fi
}


# Verify the security string.
check()
{
  CHECK=$(echo "$1" | md5sum | awk '{print $1}')
  if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
    echo "$0: cannot complete operation, please check documentation." 1>&2
    exit 2;
  fi
}

# Main routine, perform action requested on command line.
case ${1:-status} in
  sysboot )
    sysboot
    ;;

  start | restart )
    check "$2"
    stop
    start
    ;;

  status )
    status
    ;;

  stop )
    check "$2"
    stop
    ;;

  help )
    perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
    ;;

  version )
    echo "$REQMGR2MS_VERSION"
    ;;

  * )
    echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
    exit 1
    ;;
esac
