#!/usr/bin/env python
"""
Requests a machine host certificate by acessing gridca.cern.ch
protected pages using user certificate authentication.
"""
from subprocess import Popen, PIPE
from sys import argv, exit, stderr, version_info
from urllib2 import HTTPCookieProcessor, AbstractHTTPHandler, \
                    urlopen, build_opener, install_opener
from urllib import urlencode
from urlparse import urljoin
import os, re
try:
  from httplib import HTTPSConnection
except:
  from httplib import HTTPS as HTTPSConnection
from HTMLParser import HTMLParser

DEBUG = False
ssl_key_file = None
ssl_cert_file = None

if DEBUG:
  def debug_init(self, **kwargs): self._debuglevel = 1
  AbstractHTTPHandler.__init__ = debug_init

class X509HTTPS(HTTPSConnection):
  def __init__(self, host, *args, **kwargs):
    HTTPSConnection.__init__(self, host, key_file = ssl_key_file,
			     cert_file = ssl_cert_file, **kwargs)

class X509Auth(AbstractHTTPHandler):
  def default_open(self, req):
    return self.do_open(X509HTTPS, req)

def parse_form_fields(page):
  """Parses and decodes HTML form inputs with 'name' and 'value'."""
  h = HTMLParser()
  result = {}
  for item in page.split('<input '):
    if item.find('name=') != -1 and item.find('value=') != -1:
      key = item.split('name="')[1].split('"')[0]
      val = h.unescape(item.split('value="')[1].split('"')[0])
      result[key] = val
  return result

def sso_auth(auth_url):
  """Authenticate to CERN SSO for `url`."""
  # Instantiate html parser to use when unescaping html
  h = HTMLParser()

  # Setup HTTP handlers
  cookieproc = HTTPCookieProcessor()
  opener = build_opener(cookieproc)
  opener.addheaders = [('User-agent', 'Mozilla/5.0')]
  install_opener(opener)

  # Send the first request which sets the auth cookie and leads to
  # redirection ending at CERN SSO login page. Grab the cert login
  # link from that page.
  login = urlopen(auth_url)
  login_page = login.read()
  m = re.search(r'href="(auth/sslclient/[^"]*)"', login_page)
  assert m, "No cert login link at <%s>" % login.geturl()
  login_url = urljoin(login.geturl(), h.unescape(m.group(1)))

  # Redo opener to include X509 cert auth. Keep cookies.
  opener = build_opener(cookieproc, X509Auth())
  opener.addheaders = [('User-agent', 'Mozilla/5.0')]
  install_opener(opener)

  # Now login with cert. This sets authentication cookie, and yields
  # a form we are meant to re-submit to complete the authentication.
  jump_page = urlopen(login_url).read()

  sso_data = parse_form_fields(jump_page)
  m = re.search(r'<form[^>]* action="([^"]*?)">', jump_page)
  assert m, "No form to post after sso auth?"
  master_url = h.unescape(m.group(1))

  # Reset opener to remove the X509 authentication but keep cookies.
  opener = build_opener(cookieproc)
  opener.addheaders = [('User-agent', 'Mozilla/5.0')]
  install_opener(opener)

  # Repost to target URL and parse out form parameters on destination.
  document = urlopen(master_url, urlencode(sso_data))
  page = document.read()
  return document.geturl(), parse_form_fields(page), page

def sso_request(url, args):
  """Get data from a service behind CERN SSO."""
  document = urlopen(url, urlencode(args))
  page = document.read()
  return document.geturl(), parse_form_fields(page), page

if __name__ == "__main__":
  if not ssl_key_file:
    x509_path = os.getenv("X509_USER_KEY", None)
    if x509_path and os.path.exists(x509_path):
      ssl_key_file = x509_path

  if not ssl_cert_file:
    x509_path = os.getenv("X509_USER_CERT", None)
    if x509_path and os.path.exists(x509_path):
      ssl_cert_file = x509_path

  if not ssl_key_file:
    x509_path = os.getenv("HOME") + "/.globus/userkey.pem"
    if os.path.exists(x509_path):
      ssl_key_file = x509_path

  if not ssl_cert_file:
    x509_path = os.getenv("HOME") + "/.globus/usercert.pem"
    if os.path.exists(x509_path):
      ssl_cert_file = x509_path

  if not ssl_key_file or not os.path.exists(ssl_key_file):
    print >>stderr, "no certificate private key file found"
    exit(1)

  if not ssl_cert_file or not os.path.exists(ssl_cert_file):
    print >>stderr, "no certificate public key file found"
    exit(1)

  print "Using SSL X509 key", ssl_key_file, "certificate", ssl_cert_file

  if len(argv) != 3:
    print 'Usage: %s request.csr result.der' % argv[0]
    exit(1)

  # Authenticate to CERN SSO.
  ca_url = "https://ca.cern.ch/ca/host/HostSelection.aspx?template=ee2host&instructions=openssl"
  url, form_data, initial_page = sso_auth(ca_url)

  # Unfortunately, gridca.cern.ca returns /gridca as initial page, so
  # send a first request to RequestHostCertificate.aspx, for good."
  url, form_data, initial_page = sso_request(ca_url, form_data)

  # The previous re-sets the authentication cookie, and yields
  # a form we are meant to re-submit to complete the re-authentication.
  url, form_data, hostname_page = sso_request(ca_url, form_data)

  # Prepare the cert request and get the host name from it.
  req, pem = argv[1:]
  host = re.match(r"^subject=/CN=(.*)$",
		  Popen(["openssl", "req", "-in", req, "-noout", "-subject"], stdout=PIPE)
		  .communicate()[0]).group(1)
  reqdata = open(req).read()

  # Submit the form with the host name.
  form_data['ctl00$ctl00$ctl00$NICEMasterPageBodyContent$SiteContentPlaceholder$HostSiteContentPlaceholder$ManagedHostSelection$TbHostName'] = host
  url, form_data, hostreq_page = sso_request(ca_url, form_data)

  # Now submit the certificate request. Note the request
  # goes to "url", not "ca_url".
  form_data['ctl00$ctl00$ctl00$NICEMasterPageBodyContent$SiteContentPlaceholder$HostSiteContentPlaceholder$TbCreateCertificateRequest'] = reqdata
  form_data['ctl00$ctl00$ctl00$NICEMasterPageBodyContent$SiteContentPlaceholder$HostSiteContentPlaceholder$ExpirationRemindersCtrl$DdlReminders'] = 'Requester'
  del(form_data['ctl00$ctl00$ctl00$NICEMasterPageBodyContent$SiteContentPlaceholder$HostSiteContentPlaceholder$UploadButton'])
  del(form_data['ctl00$ctl00$ctl00$NICEMasterPageBodyContent$SiteContentPlaceholder$HostSiteContentPlaceholder$UploadCertificateRequest'])
  url, form_data, downloadcert_page = sso_request(url, form_data)

  # Find the link for downloading certificate PEM file.
  m = re.search(r'href="(host.cert\?template=EE2Host&requestID=.*encoding=b64)"', downloadcert_page)
  assert m, "No PEM download link at <%s>" % url
  pem_url = urljoin(url, HTMLParser().unescape(m.group(1)))

  # Finally download the PEM file.
  data = urlopen(pem_url).read()
  open(pem, "w").write(data)
  exit(0)
