#!/bin/sh

DIR=${1-/data}
cd $DIR
sudo rsync -zavuH -e 'ssh -c arcfour' --rsync-path="sudo rsync" -f '- **/phedex*/cache' cmsweb@vocms136.cern.ch:/data/ ./
sudo rsync -zavuH -e 'ssh -c arcfour' --rsync-path="sudo rsync" -f '- **/phedex*/cache' cmsweb@vocms163.cern.ch:/data/ ./
sudo rsync -zavuH -e 'ssh -c arcfour' --rsync-path="sudo rsync" -f '- /pool/store/*' -f '- **/download/[a-y]*' -f '- **/download/z[^ah]*' -f '- **/phedex*/cache' cmsweb@vocms0740.cern.ch:/data/ ./
sudo /usr/sbin/ncm-ncd --configure grid_service_certificates
