#!/bin/sh

### Usage: InstallDev -h
### Usage: InstallDev [-A arch] [-d DIR] -s image -v VER -p PKGS [-r A=B] [-a AUTH]
### Usage: InstallDev [-A arch] [-d DIR] -s post[:HOST] -v VER -p PKGS
### Usage: InstallDev [-A arch] [-d DIR] -s status[:what]
### Usage: InstallDev [-A arch] [-d DIR] -s start[:what]
### Usage: InstallDev [-A arch] [-d DIR] -s stop[:what]

usage()
{
  perl -ne '/^### Usage:/ && do { s/^### ?//; print }' < $0
  exit 1
}

help()
{
  perl -ne '/^###/ && do { s/^### ?//; print }' < $0
  exit 0
}

STAGE= VER= REPO= ACFG= PKGS= ARCH=
for arg; do
  case $arg in
    -d) cd "$2" || exit $?; shift; shift ;;
    -A) ARCH="-A $2"; shift; shift ;;
    -s) STAGE="$2"; shift; shift ;;
    -v) VER="$2"; shift; shift ;;
    -r) REPO="-r $2"; shift; shift ;;
    -a) ACFG="-p $2"; rm -f $2/auth/wmcore/header-auth-key*; shift; shift ;;
    -p) PKGS="$2"; shift; shift ;;
    -h) help ;;
    --) shift; break ;;
    -*) usage ;;
  esac
done

[ $# = 0 ] || usage
[ -d cfg/admin ] || usage
[ X"$STAGE" = X ] && usage

case $STAGE in
  status:* | start:* | stop:* | post:* )
    WHAT=${STAGE#*:} STAGE=${STAGE%:*} ;;
  post )
    WHAT=$(hostname -s) ;;
  status | start | stop )
    WHAT="*" ;;
esac

case $STAGE in
  image | post )
    [ X"$PKGS" = X ] && usage
    [ X"$VER" = X ] && usage
    ;;
esac

case $STAGE in
  image )
    set -ex
    $PWD/cfg/Deploy $ARCH $ACFG -t $VER -a -s prep $PWD $PKGS
    $PWD/cfg/admin/ProxySeed -t dev -d $PWD/$VER/auth/proxy
    sudo -H -u _sw bashs -lc "$PWD/cfg/Deploy $ARCH $ACFG $REPO -t $VER -a -s sw $PWD $PKGS"
    $PWD/cfg/Deploy $ARCH $REPO -t $VER -a -s post $PWD $PKGS
    ;;

  post )
    set -ex
    $PWD/cfg/Deploy $ARCH -H $WHAT $REPO -t $VER -a -s post $PWD $PKGS
    ;;

  start | status | stop )
    set -e
    for f in enabled/$WHAT; do
      app=${f#*/}; case $app in frontend) u=root ;; * ) u=_$app ;; esac
      (set -ex; sudo -H -u $u bashs -lc \
       "$PWD/current/config/$app/manage $STAGE 'I did read documentation'")
    done
    ;;

  * )
    echo "$STAGE: bad stage, try -h for help" 1>&2
    exit 1
    ;;
esac

exit 0
