#!/bin/sh

# Synchronise zipped log archives to AFS area.
BASEDIR=${1-$(cd $(dirname $0)/../../.. && pwd)}
ARCHDIR=${2-/afs/cern.ch/cms/cmsweb/log-archive/$(hostname -s | tr [:upper:] [:lower:])}

[ -d $BASEDIR/logs ] || { echo "$BASEDIR/logs: no such directory" 1>&2; exit 1; }
{ [ -d $ARCHDIR ] && [ -w $ARCHDIR ]; } || { "$ARCHDIR: not a writeable directory" 1>&2; exit 1; }

for applogs in $(find $BASEDIR/logs -depth -type d); do
  [ -d $applogs ] || continue
  [ -f $applogs/.noarchive ] && continue

  case $applogs in
    */frontend )
      # Archive front-end logs to secure area.
      ionice -c3 rsync --delete -f '-s *.txt' \
        -auz --no-group -e 'ssh -c arcfour' $applogs/ $ARCHDIR/ ||
        { echo "failed to synchronise logs to $ARCHDIR: $?" 1>&2; exit 5; }
      ;;

    * )
      # For now back-end server logs aren't interesting.
      ;;
  esac
done
