#!/bin/sh

#Split CouchDB logs according to the rules defined in couchdb-logrotate.conf

for host in vocms0{127,131,132,140,141,142}; do
  OUT=$(ssh $host "sudo logrotate /data/srv/current/config/couchdb/couchdb-logrotate.conf")
  if [ "$OUT" == "ROTATE" ]; then
    mv /build/srv-logs/$host/couchdb/{couch.log,couch-$(date +%Y%m%d).log}
    rm -f /build/srv-logs/$host/couchdb/couch.old.log
  fi
done
