#!/bin/sh

# DQM daily maintenance script.
#
# See the operations documentation on how to use this script:
#   https://twiki.cern.ch/twiki/bin/view/CMS/DQMGuiProduction

######################################################################
# Figure out where the server is based on this script's location.
ME=$(basename $(dirname $0))
TOP=$(cd $(dirname $0)/../../.. && pwd)
STATEDIR=$TOP/state/$ME
LOGDIR=$TOP/logs
HOST=$(hostname -s | tr [:upper:] [:lower:])

if [ X"$STATEDIR" = X ]; then
  echo "$0: cannot figure out server location"
  exit 1
fi

cd $STATEDIR
if [ $(find $STATEDIR -maxdepth 2 -type d -name sessions | wc -l) = 0 ]; then
  echo "$0: server location '$STATEDIR' is wrong"
  exit 1
fi

mkdir $STATEDIR/.nodaily || { echo "$0: daily cannot run"; exit 1; }
trap "rmdir $STATEDIR/.nodaily" 0 1 2 15

######################################################################
# Purge old sessions.
for dir in $(find $STATEDIR -maxdepth 2 -type d -name sessions); do
  find "$dir" -type f -mmin +120 | xargs rm -f
done

######################################################################
# Delete transfered zip files
for i in offline relval dev; do
  ZIPREPO=$STATEDIR/$i/zipped
  CLEANDIR=$STATEDIR/$i/agents/clean
  if [ -d $ZIPREPO ] && [ -d $CLEANDIR ]; then
    for cf in $(find $CLEANDIR -name \*.zinfo); do
      set -e
      ZIPPATH=$ZIPREPO/$(python -c "a=eval(file('$cf').read());print a['zpath']")
      if [ -e $ZIPPATH ]; then
        rm $ZIPPATH $cf
      else
        mv $cf ${cf}.bad
      fi
      set +e
    done
  fi
done

####################################################################
# See if we are in online to do some more clean up. Move old
# zip archives to the filer
case $HOST in dqm-c2d07-* )
  LOGFILER=/dqmdata/logs/$HOST
  for a in $(find  $LOGDIR -name \*.zip -mtime +2)
  do
    service=$(dirname ${a/$LOGDIR\//})
    [ ! -d $LOGFILER/$service ] && mkdir -p $LOGFILER/$service
    mv $a $LOGFILER/$service
  done
  ;;
esac
