server.service('Online',          'https://cmsweb.cern.ch/dqm/online')
server.service('Online test',     'https://cmsweb.cern.ch/dqm/online-test')
server.service('Online playback', 'https://cmsweb.cern.ch/dqm/online-playback')
server.service('Offline',         'https://cmsweb.cern.ch/dqm/offline')
server.service('Offline test',    'https://cmsweb.cern.ch/dqm/offline-test')
server.service('RelVal',          'https://cmsweb.cern.ch/dqm/relval')
server.service('RelVal test',     'https://cmsweb.cern.ch/dqm/relval-test')
