#!/bin/bash
# fetch (download or copy) the update files and store them in $TMPDIR
# the list of files to be fetched (downloaded or copied) is currently stored in
# ./*.conf, where * is a param to download()

# usage message
usage="Usage: fetch_metadata <location to store DAS metadata>"

# check input
if [ $# -eq 0 ] || [ "$1" == "-h" ] || [ "$1" == "-help" ] || [ "$1" == "--help" ]; then
    echo $usage
    exit 0
fi
if [ $# -ne 1 ]; then
    echo $usage
    exit 1
fi

TMPDIR="$1"
if [ -d $TMPDIR ]; then
    touch $TMPDIR/test_permission
    if [ $? -eq 1 ]; then
        echo "Not enough permission to write to $TMPDIR"
        exit 1
    fi
else
    echo "Directory $TMPDIR does not exists"
    exit 1
fi

CFGDIR=$(dirname "$0") # config files are stored in same dir
RE_URL='(https|http)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|].js'

# get or download a file
getfile()
{
    local file=$1
    local fname=`basename $file`
    # Fetch DAS map JSON file from given URI
    if  [ -f "$file" ]; then
        cp "$file" "$TMPDIR/$fname"
    elif [[ "$file" =~ $RE_URL ]]; then
        # download or fail silently
        curl -s -f "$file" > "$TMPDIR/$fname"
        status=$?
        if [ $status -ne 0 ]; then
            echo "failure downloading"
            exit -1
        fi

    else
        echo "Invalid update file name: $file"
        echo "please provide either a URL or full file name"
    fi
}

# download
download(){
    CFG=$CFGDIR/$1.conf

    # download the files
    while read -r file; do
        if [[ "$file" =~ '.js' ]]; then
            echo "Get $file"
            getfile "$file"
        fi
    done < "$CFG"
}

echo "Downloading DAS maps into: $TMPDIR"

# cleanup the temporary dir used for downloading
rm -rf "$TMPDIR"
mkdir -p "$TMPDIR"

# download the files
download "dasmaps"
download "keylearning"
download "inputvals"
