#!/bin/sh

##H Usage: manage ACTION [SECURITY-STRING]
##H
##H Available actions:
##H   help        show this help
##H   version     get current version of the service
##H   status      show current service's status
##H   sysboot     start server from crond if not running
##H   restart     (re)start the service
##H   start       (re)start the service
##H   stop        stop the service
##H   dbclean [minutes]   clean old docs from req/stat db older than [minutes] (def. 2 weeks)
##H
##H For more details please refer to operations page:
##H   https://svnweb.cern.ch/trac/CMSDMWM/wiki/StageManagerDeployment

if [ $(id -un)  = cmsweb ]; then
  echo "ERROR: please use another account" 1>&2
  exit 1
fi

echo_e=-e bsdstart=bsdstart
case $(uname) in Darwin )
  md5sum() { md5 -r ${1+"$@"}; }
  echo_e= bsdstart=start
  ;;
esac

ME=$(basename $(dirname $0))
TOP=$(cd $(dirname $0)/../../.. && pwd)
ROOT=$(cd $(dirname $0)/../.. && pwd)
LOGDIR=$TOP/logs/$ME
STATEDIR=$TOP/state/$ME
CFGDIR=$(dirname $0)
CFGFILE=$CFGDIR/AgentOpts.txt
CFGOPTS=$(cat $CFGFILE)
COLOR_OK="\\033[0;32m"
COLOR_WARN="\\033[0;31m"
COLOR_NORMAL="\\033[0;39m"

. $ROOT/apps/$ME-agent/etc/profile.d/init.sh

# Start service conditionally on crond restart.
sysboot()
{
  if [ $(pgrep -u $(id -u) -f "StageManagerAgent.py" | wc -l) = 0 ]; then
    start
  fi
}

# Start the service.
start()
{
  cd $STATEDIR
  echo "starting $ME"
  python -u $STAGEMANAGER_AGENT_ROOT/$PYTHON_LIB_SITE_PACKAGES/StageManager/Agents/StageManagerAgent.py \
         $CFGOPTS </dev/null 2>&1 |
    rotatelogs $LOGDIR/stagemanager-%Y%m%d.log 86400 >/dev/null 2>&1 &
}

# Stop the service.
stop()
{
  echo "stopping $ME"
  for PID in $(pgrep -u $(id -u) -f "StageManagerAgent.py" | sort -rn); do
    PSLINE=$(ps -o pid=,$bsdstart=,args= $PID |
             perl -n -e 'print join(" ", (split)[0..6])')
    echo "Stopping $PID ($PSLINE):"
    kill -9 $PID
  done
}

# Check if the server is running.
status()
{
  pid=$(pgrep -u $(id -u) -f "StageManagerAgent.py" | sort -n)
  if [ X"$pid" = X ]; then
    echo $echo_e "$ME is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}."
  else
    echo $echo_e "$ME is ${COLOR_OK}RUNNING${COLOR_NORMAL}, PID" $pid
  fi
}

dbclean()
{
  min=$(($1)); [ $min -lt 1 ] && min=20160 # defaults to 2 weeks
  age=$(($(date +%s)-$min*60))
  sitename=$(egrep -o 'T[0-3]_[A-Z][A-Z]_[A-Z0-9]+' $CFGFILE \
             | tr '[:upper:]' '[:lower:]')

  for db in requests statistics; do
    docs=$(curl -s "localhost:5984/${sitename}_$db/_design/$db/_view/doc_age?reduce=false" \
           | grep '^{"id":"[^_]' | awk -F\" '{print $4,$8,$11}' | tr -d ":},\r")
    if [ -n "$docs" ]; then
      echo "$docs" | while read ID REV DOCAGE; do
        [ ${DOCAGE%.*} -gt $age ] || \
          curl -s -X DELETE localhost:5984/${sitename}_$db/$ID?rev=$REV > /dev/null
      done
    fi
  done
}

# Verify the security string.
check()
{
  CHECK=$(echo "$1" | md5sum | awk '{print $1}')
  if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
    echo "$0: cannot complete operation, please check documentation." 1>&2
    exit 2;
  fi
}

# Main routine, perform action requested on command line.
case ${1:-status} in
  sysboot )
    if ps -oargs= $PPID | grep -q crond; then
      sysboot
    else
      echo "$0: sysboot is for cron only" 1>&2
      exit 1
    fi
    ;;

  start | restart )
    check "$2"
    stop
    start
    ;;

  status )
    status
    ;;

  stop )
    check "$2"
    stop
    ;;

  dbclean )
    dbclean $2
    ;;

  help )
    perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
    ;;

  version )
    echo "$STAGEMANAGER_AGENT_VERSION"
    ;;

  * )
    echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
    exit 1
    ;;
esac
