#!/bin/bash

ID="VISUALIZATION-TESTSERVICE"
DIR="/afs/cern.ch/cms/CAF/CMSCOMM/COMM_GLOBAL/EventDisplay/RootFileTempStorageArea/Log"
AV=0  # availability

[ "$(find $DIR/ -name Skim\*log -mmin -60|tail -1|wc -l)" = "1" ] &&
  AV=100

cat << EOXML
<?xml version="1.0" encoding="utf-8"?>
<serviceupdate xmlns="http://sls.cern.ch/SLS/XML/update">
  <id>$ID</id>
  <availability>$AV</availability>
  <timestamp>$(date +%FT%T%:z)</timestamp>
</serviceupdate>
EOXML
