#!/bin/sh

##H Usage: manage ACTION [ARG] [SECURITY-STRING]
##H
##H Available actions:
##H   help        show this help
##H   version     get current version of the service
##H   status      show current service's status
##H   sysboot     start server from crond if not running
##H   restart     (re)start the service
##H   start       (re)start the service
##H   stop        stop the service
##H   cron ARG    run cronjob named ARG (dataframe|models|verify)
##H

if [ $(id -un)  = cmsweb ]; then
  echo "ERROR: please use another account" 1>&2
  exit 1
fi

echo_e=-e
case $(uname) in Darwin )
  md5sum() { md5 -r ${1+"$@"}; }
  echo_e=
  ;;
esac

ME=$(basename $(dirname $0))
TOP=$(cd $(dirname $0)/../../.. && pwd)
ROOT=$(cd $(dirname $0)/../.. && pwd)
LOGDIR=$TOP/logs/$ME
STATEDIR=$TOP/state/$ME
COLOR_OK="\\033[0;32m"
COLOR_WARN="\\033[0;31m"
COLOR_NORMAL="\\033[0;39m"

. $ROOT/apps/wmarchive/etc/profile.d/init.sh

export WMARCHIVE_ROOT
export WMA_STATIC_ROOT=$WMARCHIVE_ROOT/data
export WMARCHIVE_PORT=8247
export PYTHONUNBUFFERED=1
export JAVA_JDK_ROOT
export JAVA_HOME=$JAVA_JDK_ROOT

# kerberos
export WMAKEYTAB=$STATEDIR/wma.keytab
principal=`klist -k $WMAKEYTAB | tail -1 | awk '{print $2}'`
kinit $principal -k -t $WMAKEYTAB

# GRID
export X509_USER_PROXY=$STATEDIR/proxy/proxy.cert
export X509_USER_CERT=$X509_USER_PROXY
export X509_USER_KEY=$X509_USER_PROXY
export WMARCHIVE_CONFIG=$ROOT/config/$ME/wmarch_config.py
export WMARCHIVE_ERROR_CODES=$WMA_STATIC_ROOT/wmexceptions.json
export WMARCHIVE_PERF_METRICS=$WMA_STATIC_ROOT/maps/metrics.json
export MONGO_URI="mongodb://localhost:8230"
export AVRO_STORAGE=$STATEDIR/avro/data
export AVRO_STORAGE_MIGRATE=$STATEDIR/avro/migrate
# area on HDFS where we'll migrate the data
export HDFS_MIGRATE=/cms/wmarchive/avro
export AVRO_SCHEMA=$STATEDIR/avro/schemas/current.avsc
export AVRO_SCHEMA_HDFS=`cat $WMARCHIVE_CONFIG | grep long_storage_uri | awk '{split($0,a,"="); print a[2]}' | sed -e 's/^[[:space:]]*//' -e "s,',,g"`
# we'll clean-up data a one day old if their storage type is avroio
export CLEANUP_TSTAMP=1d
export CLEANUP_STYPE="avroio"

cd $STATEDIR
host=`hostname -s`

# Start service conditionally on crond restart.
sysboot()
{
  dostart=false
  if [ $(pgrep -u $(id -u) -f "[/]wmarch" | wc -l) = 0 ]; then
      dostart=true
  fi
  $dostart && start
}

createindex()
{
    mport=`echo $MONGO_URI | awk -F: '{print $3}'`
    mongo --port $mport < $WMARCHIVE_ROOT/data/js/create_wma_indexes.js
}

start()
{
  echo "starting $ME"
  # start service
  $WMARCHIVE_ROOT/bin/wmc-httpd -r -d $LOGDIR $WMARCHIVE_CONFIG &
  $WMARCHIVE_ROOT/bin/mongo2avro \
      --mongo=$MONGO_URI --schema=$AVRO_SCHEMA \
      --odir=$AVRO_STORAGE --mdir=$AVRO_STORAGE_MIGRATE \
      --tstamp=$CLEANUP_TSTAMP --stype=$CLEANUP_STYPE \
      </dev/null 2>&1 | rotatelogs $LOGDIR/mongo2avro-%Y%m%d.log 86400 >/dev/null 2>&1 &
}

# Stop the service.
stop()
{
  echo "stopping $ME"
  for pid in $(pgrep -u $(id -u) -f "[/]wmarch_config.py"); do
      kill -9 $pid
  done
  for pid in $(pgrep -u $(id -u) -f "[/]mongo2avro"); do
      kill -9 $pid
  done
}

# Check if the server is running.
status()
{
  local pid=$(pgrep -u $(id -u) -f "[/]wmarch_config.py" | sort -n)
  if [ X"$pid" = X ]; then
    echo $echo_e "$ME $pat is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}."
  else
    echo $echo_e "$ME $pat is ${COLOR_OK}RUNNING${COLOR_NORMAL}, PID" $pid
  fi
}

# Runs actions to be done through cronjobs
cron()
{
  local action=$1
  case $action in
    migrate2hdfs )
      $WMARCHIVE_ROOT/bin/migrate2hdfs \
          --idir=$AVRO_STORAGE_MIGRATE --odir=$HDFS_MIGRATE --check --remove \
          --verbose &> $LOGDIR/migrate2hdfs.log
      ;;
    aggregate )
      $WMARCHIVE_ROOT/bin/aggregate_performance 1 --precision=hour \
          --schema $AVRO_SCHEMA_HDFS \
          --use_myspark &> $LOGDIR/aggregate_performace.log

      ;;
    cleanup )
      $WMARCHIVE_ROOT/bin/clean_performance --interval=3m &> $LOGDIR/cleanup.log
      ;;
    * )
      echo "You must specify the cron action to run: mongo2avro|mongocleanup "
      exit 1
      ;;
  esac
}

# Verify the security string.
check()
{
  CHECK=$(echo "$1" | md5sum | awk '{print $1}')
  if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
    echo "$0: cannot complete operation, please check documentation." 1>&2
    exit 2;
  fi
}

# Main routine, perform action requested on command line.
case ${1:-status} in
  sysboot )
    sysboot
    ;;

  start | restart )
    check "$2"
    stop
    start
    createindex
    ;;

  status )
    status
    ;;

  stop )
    check "$2"
    stop
    ;;

  cron )
    check "$3"
    cron $2
    ;;

  help )
    perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
    ;;

  version )
    echo "$WMARCHIVE_VERSION"
    ;;

  * )
    echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
    exit 1
    ;;
esac
