#!/bin/sh

##H Usage: manage ACTION [SECURITY-STRING]
##H
##H Available actions:
##H   help        show this help
##H   version     get current version of the service
##H   status      show current service's status
##H   sysboot     start server from crond if not running
##H   restart     (re)start the service
##H   start       (re)start the service
##H   stop        stop the service
##H
##H For more details please refer to operations page:
##H   https://twiki.cern.ch/twiki/bin/view/CMS/DASOperation

if [ $(id -un)  = cmsweb ]; then
  echo "ERROR: please use another account" 1>&2
  exit 1
fi

echo_e=-e
case $(uname) in Darwin )
  md5sum() { md5 -r ${1+"$@"}; }
  echo_e=
  ;;
esac

ME=$(basename $(dirname $0))
TOP=$(cd $(dirname $0)/../../.. && pwd)
ROOT=$(cd $(dirname $0)/../.. && pwd)
CFGDIR=$(dirname $0)
LOGDIR=$TOP/logs/$ME
STATEDIR=$TOP/state/$ME
COLOR_OK="\\033[0;32m"
COLOR_WARN="\\033[0;31m"
COLOR_NORMAL="\\033[0;39m"

. $ROOT/apps/$ME/etc/profile.d/init.sh

export DAS_ROOT YUI_ROOT
export PYTHONUNBUFFERED=1
export DAS_PYTHONPATH=$DAS_ROOT/lib/python2.6/site-packages
export DAS_JSPATH=$DAS_ROOT/lib/python2.6/site-packages/src/js
export DAS_CSSPATH=$DAS_ROOT/lib/python2.6/site-packages/src/css
export DAS_TMPLPATH=$DAS_ROOT/lib/python2.6/site-packages/src/templates
export DAS_IMAGESPATH=$DAS_ROOT/lib/python2.6/site-packages/src/images
export X509_USER_PROXY=$STATEDIR/proxy/proxy.cert
export X509_USER_CERT=$X509_USER_PROXY
export X509_USER_KEY=$X509_USER_PROXY
export DAS_CONFIG=$CFGDIR/das_cms.py
export DAS_ANALYTICS=$CFGDIR/analytics_cfg.py
cd $STATEDIR

# Start service conditionally on crond restart.
sysboot()
{
  dostart=false
  if [ $(pgrep -u $(id -u) -f "[/]das_server.py" | wc -l) = 0 ]; then
      dostart=true
  fi
  if [ $(pgrep -u $(id -u) -f "[/]controller.py" | wc -l) = 0 ]; then
    dostart=true
  fi
  $dostart && start
}

# Start the service.
start()
{
  echo "starting $ME"
  python -u $DAS_PYTHONPATH/DAS/web/das_server.py \
       </dev/null 2>&1 | rotatelogs $LOGDIR/das-%Y%m%d.log 86400 >/dev/null 2>&1 &

  python -u $DAS_PYTHONPATH/DAS/analytics/controller.py $DAS_ANALYTICS \
    </dev/null 2>&1 | rotatelogs $LOGDIR/das-analytics-%Y%m%d.log 86400 >/dev/null 2>&1 &
}

# Stop the service.
stop()
{
  echo "stopping $ME"
  for pid in $(pgrep -u $(id -u) -f "[/]das_server.py"); do
      kill -9 $pid
  done

  for pid in $(pgrep -u $(id -u) -f "[/]controller.py"); do
    kill -9 $pid
  done
}

# Check if the server is running.
status()
{
  for pat in web analytics; do
    if [ $pat == "web" ]; then
      pid=$(pgrep -u $(id -u) -f "[/]das_server.py" | sort -n)
    elif [ $pat == "analytics" ]; then
      pid=$(pgrep -u $(id -u) -f "[/]controller.py" | sort -n)
    fi
    if [ X"$pid" = X ]; then
      echo $echo_e "$ME $pat is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}."
    else
      echo $echo_e "$ME $pat is ${COLOR_OK}RUNNING${COLOR_NORMAL}, PID" $pid
    fi
  done
}

# Verify the security string.
check()
{
  CHECK=$(echo "$1" | md5sum | awk '{print $1}')
  if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
    echo "$0: cannot complete operation, please check documentation." 1>&2
    exit 2;
  fi
}

# Main routine, perform action requested on command line.
case ${1:-status} in
  sysboot )
    if ps -oargs= $PPID | grep -q crond; then
      sysboot
    else
      echo "$0: sysboot is for cron only" 1>&2
      exit 1
    fi
    ;;

  start | restart )
    check "$2"
    stop
    start
    ;;

  status )
    status
    ;;

  stop )
    check "$2"
    stop
    ;;

  help )
    perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
    ;;

  version )
    echo "$DAS_VERSION"
    ;;

  * )
    echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
    exit 1
    ;;
esac
