#!/bin/sh

##H Usage: manage ACTION [SECURITY-STRING]
##H
##H Available actions:
##H   help        show this help
##H   version     get current version of the service
##H   status      show current service's status
##H   sysboot     start server from crond if not running
##H   restart     (re)start the service
##H   start       (re)start the service
##H   stop        stop the service
##H   bootstrap   fetch data from services: accepted input values and what fields available in services results
##H   fetchmaps   fetch DAS maps
##H   uploadmaps  upload new DAS maps into MongoDB
##H
##H For more details please refer to operations page:
##H   https://twiki.cern.ch/twiki/bin/view/CMS/DASOperation

if [ $(id -un)  = cmsweb ]; then
  echo "ERROR: please use another account" 1>&2
  exit 1
fi

echo_e=-e
case $(uname) in Darwin )
  md5sum() { md5 -r ${1+"$@"}; }
  echo_e=
  ;;
esac

ME=$(basename $(dirname $0))
TOP=$(cd $(dirname $0)/../../.. && pwd)
ROOT=$(cd $(dirname $0)/../.. && pwd)
CFGDIR=$(dirname $0)
LOGDIR=$TOP/logs/$ME
STATEDIR=$TOP/state/$ME
COLOR_OK="\\033[0;32m"
COLOR_WARN="\\033[0;31m"
COLOR_NORMAL="\\033[0;39m"

. $ROOT/apps/$ME/etc/profile.d/init.sh

export DAS_ROOT YUI_ROOT
export PYTHONUNBUFFERED=1
export DAS_PYTHONPATH=$DAS_ROOT/lib/python2.6/site-packages
export DAS_JSPATH=$DAS_ROOT/lib/python2.6/site-packages/src/js
export DAS_CSSPATH=$DAS_ROOT/lib/python2.6/site-packages/src/css
export DAS_TMPLPATH=$DAS_ROOT/lib/python2.6/site-packages/src/templates
export DAS_IMAGESPATH=$DAS_ROOT/lib/python2.6/site-packages/src/images
export X509_USER_PROXY=$STATEDIR/proxy/proxy.cert
export X509_USER_CERT=$X509_USER_PROXY
export X509_USER_KEY=$X509_USER_PROXY
export DAS_CONFIG=$CFGDIR/das_cms.py
export DAS_KWS_IR_INDEX=$STATEDIR/kws_index
export STAGEDIR=$STATEDIR/stagingarea
mkdir -p $STAGEDIR

cd $STATEDIR
host=`hostname`

# helper function to check MongoDB
check_mongodb() {
  mongo_pid=`pgrep -f "bin/mongod"`
  if [ -n "$mongo_pid" ]; then
      echo "MongoDB pid=$mongo_pid"
  else
      echo "MongoDB is not ready, unable to start DAS"
      exit 1
  fi
}

# deploy DAS and DAS KWS maps into stagedir area
deploy_das_maps(){
  if [ ! -f $STAGEDIR/das_maps_status ]; then
      # fresh release, need to copy maps from release area
      cp $DAS_PYTHONPATH/DAS/services/cms_maps/*.js $STAGEDIR
      cp $DAS_PYTHONPATH/DAS/kws_data/db_dumps/*.js $STAGEDIR
      # mark that we updated MongoDB with DAS maps
      echo "Release maps: `date`" > $STAGEDIR/das_maps_status
  fi
}

# Start service conditionally on crond restart.
sysboot()
{
  dostart=false
  if [ $(pgrep -u $(id -u) -f "[/]das_server.py" | wc -l) = 0 ]; then
      dostart=true
  fi
  $dostart && start
}

start()
{
  echo "starting $ME"
  case $host in vocms133 ) tbed="_testbed" dbspace="_int";; * ) tbed="" dbspace="_prod";; esac
  deploy_das_maps
  local mapfile=$STAGEDIR/das${tbed}_maps_dbs${dbspace}.js
  local kwsmaps=$STAGEDIR
  DAS_MAP_FILE=$mapfile DAS_KWS_MAPS=$kwsmaps $DAS_ROOT/bin/das_server start \
      </dev/null 2>&1 | rotatelogs $LOGDIR/das-%Y%m%d.log 86400 >/dev/null 2>&1 &
}

# Stop the service.
stop()
{
  echo "stopping $ME"
  for das_pid in $(pgrep -u $(id -u) -f "[/]das_server"); do
      kill -9 $das_pid
  done
}

# Check if the server is running.
status()
{
  local pid=$(pgrep -u $(id -u) -f "[/]das_server" | sort -n)
  if [ X"$pid" = X ]; then
    echo $echo_e "$ME $pat is ${COLOR_WARN}NOT RUNNING${COLOR_NORMAL}."
  else
    echo $echo_e "$ME $pat is ${COLOR_OK}RUNNING${COLOR_NORMAL}, PID" $pid
  fi
}

# download metadata and stage it for update
# change is applied on next updatedata() call
fetch_metadata(){
  set -e
  # clean-up STEGEDIR area
  rm -f $STAGEDIR/*.js $STAGEDIR/*-schema-stamp

  # fetch DAS maps
  $CFGDIR/metadata_updater/fetch_metadata $STAGEDIR

  # mark that we updated MongoDB with DAS maps
  echo "Fetched maps: `date`" > $STAGEDIR/das_maps_status
  set +e
}

# upload DAS & KWS maps into MognoDB
upload_das_maps(){
  set -e
  # choose appropriate dasmaps to use
  case $host in vocms133 ) tbed="_testbed" dbspace="_int";; * ) tbed="" dbspace="_prod";; esac
  local dasmaps=$STAGEDIR/das${tbed}_maps_dbs${dbspace}.js

  # upload DAS and KWS maps into MongoDB
  $DAS_ROOT/bin/das_update_database $dasmaps $STAGEDIR

  set +e
}

# upload metadata to MongoDB
upload_metadata(){
  set -e
  # check if MongoDB is present
  check_mongodb

  # upload DAS maps
  upload_das_maps

  # mark that we updated MongoDB with DAS maps
  echo "Updated maps: `date`" > $STAGEDIR/das_maps_status
  set +e
}

# reset DAS metadata (dasmaps, etc) to the default coming from installation
reset_metadata(){
  set -e
  # clean timestamps
  rm -f $STAGEDIR/*-schema-stamp

  # copy DAS maps from release to staging area
  cp -f $DAS_PYTHONPATH/DAS/services/cms_maps/*.js $STAGEDIR

  # upload DAS maps
  upload_das_maps

  # mark that we updated MongoDB with DAS maps
  echo "Release maps: `date`" > $STAGEDIR/das_maps_status
  set +e
}

# Bootstrap keyword search
bootstrap()
{
  set -e
  echo "starting keyword search bootstrap (values, fields)"
  das_bootstrap_kws
  echo "bootstrap done"
  set +e
}

# Verify the security string.
check()
{
  CHECK=$(echo "$1" | md5sum | awk '{print $1}')
  if [ $CHECK != 94e261a5a70785552d34a65068819993 ]; then
    echo "$0: cannot complete operation, please check documentation." 1>&2
    exit 2;
  fi
}

# Main routine, perform action requested on command line.
case ${1:-status} in
  sysboot )
    sysboot
    ;;

  start | restart )
    check "$2"
    stop
    start
    ;;

  status )
    status
    ;;

  resetmaps )
    check "$2"
    stop
    reset_metadata
    upload_metadata
    start
    ;;

  updatemaps )
    check "$2"
    stop
    fetch_metadata
    upload_metadata
    start
    ;;

  stop )
    check "$2"
    stop
    ;;

  help )
    perl -ne '/^##H/ && do { s/^##H ?//; print }' < $0
    ;;

  bootstrap )
    bootstrap
    ;;

  version )
    echo "$DAS_VERSION"
    ;;

  * )
    echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
    exit 1
    ;;
esac
