#!/bin/zsh

# Overview daily maintenance script.
#
# See the operations documentation on how to use this script:
# https://twiki.cern.ch/twiki/bin/view/CMS/OverviewDeployment

######################################################################
# Figure out where the server is based on this script's location.
HOST=$(hostname | tr '[:upper:]' '[:lower:]' | sed 's/\..*//')
HERE=$(dirname $(dirname $0))
FILER=$(dirname $(dirname $0))
[ X"$HERE" = X ] && { echo "$0: cannot figure out server location"; exit 1; }
[ -d "$HERE/server" ] || { echo "$0: server location '$HERE' is wrong"; exit 1; }
[ -d "$FILER/logarch" ] || { echo "$0: filer location '$FILER' is wrong"; exit 1; }
mkdir $HERE/.nodaily || { echo "$0: daily cannot run"; exit 1; }
trap "rmdir $HERE/.nodaily" 0 1 2 15

######################################################################
for i in server; do
  # Purge old sessions.
  find "$HERE/$i/www/sessions" -type f -mmin +120 | xargs rm -f

  # File away server logs.
  for f in $(find $HERE/$i -name '*log-20*.txt' -mtime +0 | sort); do
    set -e
    [ -f "$f" ] || continue
    item=${${f#$HERE/$i/}%/*}
    month=$(echo "$f" | perl -pe 's|.*log-||; s|^([0-9]{6}).*|$1|')
    case $month in 20[0-9][0-9][01][0-9] ) ;; * )
      echo "$f: could not determine month from log file name (got: $month)"
      continue ;;
    esac

    mkdir -p $FILER/logarch/overview-$i-$HOST/$item
    zip -9Tmojq $FILER/logarch/overview-$i-$HOST/$item/$month.zip $f
    set +e
  done
done
