def ecallayout(i, p, *rows): i[p] = DQMItem(layout=rows)

ecallayout(dqmitems, 'MCLayouts/Ecal/000 EcalSimHitsValidation Gun Momentum',[{'path': 'EcalHitsV/EcalSimHitsValidation/EcalSimHitsValidation Gun Momentum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/001 EcalSimHitsValidation Gun Eta',[{'path': 'EcalHitsV/EcalSimHitsValidation/EcalSimHitsValidation Gun Eta'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/002 EcalSimHitsValidation Gun Phi',[{'path': 'EcalHitsV/EcalSimHitsValidation/EcalSimHitsValidation Gun Phi'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/003 EcalSimHitsValidation Barrel fraction of energy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EcalSimHitsValidation Barrel fraction of energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/004 EcalSimHitsValidation Endcap fraction of energy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EcalSimHitsValidation Endcap fraction of energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/005 EcalSimHitsValidation Preshower fraction of energy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EcalSimHitsValidation Preshower fraction of energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/006 EB hits multiplicity',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB hits multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/007 EE+ hits multiplicity',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE+ hits multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/008 EE- hits multiplicity',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE- hits multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/009 EB crystals multiplicity',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB crystals multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/010 EE+ crystals multiplicity',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE+ crystals multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/011 EE- crystals multiplicity',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE- crystals multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/012 EB crystal energy spectrum',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB crystal energy spectrum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/013 EB crystal energy spectrum 2',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB crystal energy spectrum 2'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/014 EE crystal energy spectrum',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE crystal energy spectrum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/015 EE crystal energy spectrum 2',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE crystal energy spectrum 2'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/016 EB hits energy spectrum',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB hits energy spectrum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/017 EB hits energy spectrum 2',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB hits energy spectrum 2'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/018 EE hits energy spectrum',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE hits energy spectrum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/019 EE hits energy spectrum 2',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE hits energy spectrum 2'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/020 EB occupancy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB occupancy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/021 EE+ occupancy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE+ occupancy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/022 EE- occupancy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE- occupancy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/023 EB longitudinal shower profile',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB longitudinal shower profile'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/024 EE longitudinal shower profile',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE longitudinal shower profile'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/025 EB E1',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB E1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/026 EB E9',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB E9'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/027 EB E25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB E25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/028 EE E1',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE E1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/029 EE E9',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE E9'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/030 EE E25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE E25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/031 EB E1oE9',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB E1oE9'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/032 EB E1oE25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB E1oE25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/033 EB E9oE25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB E9oE25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/034 EE E1oE9',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE E1oE9'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/035 EE E1oE25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE E1oE25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/036 EE E9oE25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE E9oE25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/037 ES hits layer 1 multiplicity z+',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits layer 1 multiplicity z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/038 ES hits layer 2 multiplicity z+',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits layer 2 multiplicity z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/039 ES hits layer 1 multiplicity z-',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits layer 1 multiplicity z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/040 ES hits layer 2 multiplicity z-',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits layer 2 multiplicity z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/041 ES hits energy layer 1 z+',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits energy layer 1 z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/042 ES hits energy layer 2 z+',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits energy layer 2 z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/043 ES hits energy layer 1 z-',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits energy layer 1 z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/044 ES hits energy layer 2 z-',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits energy layer 2 z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/045 ES E1+07E2 z+',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES E1+07E2 z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/046 ES E1+07E2 z-',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES E1+07E2 z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/047 ES ene2oEne1 z+',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES ene2oEne1 z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/048 ES ene2oEne1 z-',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES ene2oEne1 z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/049 EE vs ES z+',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE vs ES z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/050 EE vs ES z-',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE vs ES z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/051 EB hits log10energy spectrum',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB hits log10energy spectrum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/052 EB hits log10energy spectrum vs normalized energy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB hits log10energy spectrum vs normalized energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/053 EB hits log10energy spectrum vs normalized energy25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB hits log10energy spectrum vs normalized energy25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/054 EE hits log10energy spectrum',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE hits log10energy spectrum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/055 EE hits log10energy spectrum vs normalized energy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE hits log10energy spectrum vs normalized energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/056 EE hits log10energy spectrum vs normalized energy25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE hits log10energy spectrum vs normalized energy25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/057 ES hits log10energy spectrum',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits log10energy spectrum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/058 ES hits log10energy spectrum vs normalized energy',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits log10energy spectrum vs normalized energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/059 EcalDigiTask Gun Momentum',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Gun Momentum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/060 EcalDigiTask Gun Eta',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Gun Eta'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/061 EcalDigiTask Gun Phi',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Gun Phi'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/062 EcalDigiTask Barrel occupancy',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel occupancy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/063 EcalDigiTask Endcap occupancy z+',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap occupancy z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/064 EcalDigiTask Endcap occupancy z-',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap occupancy z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/065 EcalDigiTask Barrel digis multiplicity',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel digis multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/066 EcalDigiTask Preshower digis multiplicity',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Preshower digis multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/067 EcalDigiTask Endcap multiplicity z+',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap multiplicity z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/068 EcalDigiTask Endcap multiplicity z-',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap multiplicity z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/069 EcalDigiTask Barrel global pulse shape',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel global pulse shape'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/070 EcalDigiTask Endcap global pulse shape',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap global pulse shape'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/071 EcalDigiTask Barrel maximum Digi over Sim ratio',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel maximum Digi over Sim ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/072 EcalDigiTask Endcap maximum Digi over Sim ratio',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap maximum Digi over Sim ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/073 EcalDigiTask Barrel maximum Digi over Sim ratio gt 10 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel maximum Digi over Sim ratio gt 10 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/074 EcalDigiTask Endcap maximum Digi over Sim ratio gt 20 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap maximum Digi over Sim ratio gt 20 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/075 EcalDigiTask Barrel maximum Digi over Sim ratio gt 100 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel maximum Digi over Sim ratio gt 100 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/076 EcalDigiTask Endcap maximum Digi over Sim ratio gt 100 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap maximum Digi over Sim ratio gt 100 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/077 EcalDigiTask Barrel ADC counts after gain switch',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC counts after gain switch'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/078 EcalDigiTask Endcap ADC counts after gain switch',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC counts after gain switch'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/079 EcalDigiTask Barrel pedestal for pre-sample',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel pedestal for pre-sample'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/080 EcalDigiTask Endcap pedestal for pre-sample',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap pedestal for pre-sample'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/081 EcalDigiTask Barrel maximum position gt 100 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel maximum position gt 100 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/082 EcalDigiTask Endcap maximum position gt 100 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap maximum position gt 100 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/083 EcalDigiTask Barrel maximum position gt 10 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel maximum position gt 10 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/084 EcalDigiTask Endcap maximum position gt 20 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap maximum position gt 20 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/085 EcalDigiTask Preshower ADC pulse 01',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Preshower ADC pulse 01'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/086 EcalDigiTask Preshower ADC pulse 02',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Preshower ADC pulse 02'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/087 EcalDigiTask Preshower ADC pulse 03',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Preshower ADC pulse 03'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/088 EcalDigiTask Barrel analog pulse 01',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 01'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/089 EcalDigiTask Barrel analog pulse 02',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 02'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/090 EcalDigiTask Barrel analog pulse 03',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 03'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/091 EcalDigiTask Barrel analog pulse 04',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 04'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/092 EcalDigiTask Barrel analog pulse 05',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 05'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/093 EcalDigiTask Barrel analog pulse 06',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 06'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/094 EcalDigiTask Barrel analog pulse 07',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 07'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/095 EcalDigiTask Barrel analog pulse 08',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 08'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/096 EcalDigiTask Barrel analog pulse 09',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 09'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/097 EcalDigiTask Barrel analog pulse 10',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 10'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/098 EcalDigiTask Barrel ADC pulse 01 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 01 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/099 EcalDigiTask Barrel ADC pulse 02 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 02 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/100 EcalDigiTask Barrel ADC pulse 03 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 03 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/101 EcalDigiTask Barrel ADC pulse 04 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 04 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/102 EcalDigiTask Barrel ADC pulse 05 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 05 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/103 EcalDigiTask Barrel ADC pulse 06 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 06 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/104 EcalDigiTask Barrel ADC pulse 07 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 07 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/105 EcalDigiTask Barrel ADC pulse 08 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 08 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/106 EcalDigiTask Barrel ADC pulse 09 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 09 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/107 EcalDigiTask Barrel ADC pulse 10 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 10 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/108 EcalDigiTask Barrel ADC pulse 01 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 01 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/109 EcalDigiTask Barrel ADC pulse 02 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 02 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/110 EcalDigiTask Barrel ADC pulse 03 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 03 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/111 EcalDigiTask Barrel ADC pulse 04 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 04 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/112 EcalDigiTask Barrel ADC pulse 05 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 05 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/113 EcalDigiTask Barrel ADC pulse 06 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 06 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/114 EcalDigiTask Barrel ADC pulse 07 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 07 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/115 EcalDigiTask Barrel ADC pulse 08 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 08 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/116 EcalDigiTask Barrel ADC pulse 09 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 09 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/117 EcalDigiTask Barrel ADC pulse 10 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 10 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/118 EcalDigiTask Barrel ADC pulse 01 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 01 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/119 EcalDigiTask Barrel ADC pulse 02 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 02 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/120 EcalDigiTask Barrel ADC pulse 03 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 03 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/121 EcalDigiTask Barrel ADC pulse 04 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 04 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/122 EcalDigiTask Barrel ADC pulse 05 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 05 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/123 EcalDigiTask Barrel ADC pulse 06 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 06 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/124 EcalDigiTask Barrel ADC pulse 07 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 07 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/125 EcalDigiTask Barrel ADC pulse 08 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 08 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/126 EcalDigiTask Barrel ADC pulse 09 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 09 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/127 EcalDigiTask Barrel ADC pulse 10 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 10 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/128 EcalDigiTask Barrel ADC pulse 01 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 01 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/129 EcalDigiTask Barrel ADC pulse 02 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 02 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/130 EcalDigiTask Barrel ADC pulse 03 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 03 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/131 EcalDigiTask Barrel ADC pulse 04 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 04 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/132 EcalDigiTask Barrel ADC pulse 05 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 05 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/133 EcalDigiTask Barrel ADC pulse 06 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 06 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/134 EcalDigiTask Barrel ADC pulse 07 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 07 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/135 EcalDigiTask Barrel ADC pulse 08 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 08 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/136 EcalDigiTask Barrel ADC pulse 09 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 09 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/137 EcalDigiTask Barrel ADC pulse 10 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 10 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/138 EcalDigiTask Barrel gain pulse 01',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 01'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/139 EcalDigiTask Barrel gain pulse 02',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 02'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/140 EcalDigiTask Barrel gain pulse 03',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 03'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/141 EcalDigiTask Barrel gain pulse 04',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 04'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/142 EcalDigiTask Barrel gain pulse 05',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 05'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/143 EcalDigiTask Barrel gain pulse 06',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 06'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/144 EcalDigiTask Barrel gain pulse 07',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 07'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/145 EcalDigiTask Barrel gain pulse 08',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 08'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/146 EcalDigiTask Barrel gain pulse 09',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 09'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/147 EcalDigiTask Barrel gain pulse 10',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 10'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/148 EcalDigiTask Endcap analog pulse 01',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 01'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/149 EcalDigiTask Endcap analog pulse 02',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 02'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/150 EcalDigiTask Endcap analog pulse 03',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 03'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/151 EcalDigiTask Endcap analog pulse 04',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 04'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/152 EcalDigiTask Endcap analog pulse 05',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 05'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/153 EcalDigiTask Endcap analog pulse 06',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 06'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/154 EcalDigiTask Endcap analog pulse 07',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 07'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/155 EcalDigiTask Endcap analog pulse 08',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 08'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/156 EcalDigiTask Endcap analog pulse 09',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 09'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/157 EcalDigiTask Endcap analog pulse 10',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 10'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/158 EcalDigiTask Endcap ADC pulse 01 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 01 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/159 EcalDigiTask Endcap ADC pulse 02 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 02 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/160 EcalDigiTask Endcap ADC pulse 03 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 03 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/161 EcalDigiTask Endcap ADC pulse 04 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 04 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/162 EcalDigiTask Endcap ADC pulse 05 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 05 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/163 EcalDigiTask Endcap ADC pulse 06 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 06 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/164 EcalDigiTask Endcap ADC pulse 07 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 07 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/165 EcalDigiTask Endcap ADC pulse 08 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 08 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/166 EcalDigiTask Endcap ADC pulse 09 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 09 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/167 EcalDigiTask Endcap ADC pulse 10 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 10 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/168 EcalDigiTask Endcap ADC pulse 01 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 01 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/169 EcalDigiTask Endcap ADC pulse 02 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 02 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/170 EcalDigiTask Endcap ADC pulse 03 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 03 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/171 EcalDigiTask Endcap ADC pulse 04 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 04 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/172 EcalDigiTask Endcap ADC pulse 05 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 05 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/173 EcalDigiTask Endcap ADC pulse 06 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 06 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/174 EcalDigiTask Endcap ADC pulse 07 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 07 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/175 EcalDigiTask Endcap ADC pulse 08 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 08 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/176 EcalDigiTask Endcap ADC pulse 09 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 09 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/177 EcalDigiTask Endcap ADC pulse 10 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 10 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/178 EcalDigiTask Endcap ADC pulse 01 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 01 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/179 EcalDigiTask Endcap ADC pulse 02 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 02 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/180 EcalDigiTask Endcap ADC pulse 03 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 03 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/181 EcalDigiTask Endcap ADC pulse 04 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 04 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/182 EcalDigiTask Endcap ADC pulse 05 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 05 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/183 EcalDigiTask Endcap ADC pulse 06 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 06 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/184 EcalDigiTask Endcap ADC pulse 07 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 07 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/185 EcalDigiTask Endcap ADC pulse 08 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 08 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/186 EcalDigiTask Endcap ADC pulse 09 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 09 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/187 EcalDigiTask Endcap ADC pulse 10 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 10 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/188 EcalDigiTask Endcap ADC pulse 01 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 01 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/189 EcalDigiTask Endcap ADC pulse 02 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 02 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/190 EcalDigiTask Endcap ADC pulse 03 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 03 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/191 EcalDigiTask Endcap ADC pulse 04 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 04 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/192 EcalDigiTask Endcap ADC pulse 05 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 05 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/193 EcalDigiTask Endcap ADC pulse 06 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 06 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/194 EcalDigiTask Endcap ADC pulse 07 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 07 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/195 EcalDigiTask Endcap ADC pulse 08 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 08 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/196 EcalDigiTask Endcap ADC pulse 09 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 09 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/197 EcalDigiTask Endcap ADC pulse 10 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 10 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/198 EcalDigiTask Endcap gain pulse 01',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 01'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/199 EcalDigiTask Endcap gain pulse 02',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 02'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/200 EcalDigiTask Endcap gain pulse 03',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 03'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/201 EcalDigiTask Endcap gain pulse 04',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 04'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/202 EcalDigiTask Endcap gain pulse 05',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 05'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/203 EcalDigiTask Endcap gain pulse 06',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 06'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/204 EcalDigiTask Endcap gain pulse 07',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 07'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/205 EcalDigiTask Endcap gain pulse 08',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 08'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/206 EcalDigiTask Endcap gain pulse 09',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 09'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/207 EcalDigiTask Endcap gain pulse 10',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 10'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/208 EcalRecHitsTask Gun Momentum',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Gun Momentum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/209 EcalRecHitsTask Gun Eta',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Gun Eta'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/210 EcalRecHitsTask Gun Phi',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Gun Phi'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/211 EcalRecHitsTask Barrel RecSimHit Ratio',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/212 EcalRecHitsTask Endcap RecSimHit Ratio',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/213 EcalRecHitsTask Preshower RecSimHit Ratio',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Preshower RecSimHit Ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/214 EcalRecHitsTask Barrel Unc RecSimHit Ratio',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel Unc RecSimHit Ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/215 EcalRecHitsTask Endcap Unc RecSimHit Ratio',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap Unc RecSimHit Ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/216 EcalRecHitsTask Barrel RecSimHit Ratio gt 3p5 GeV',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio gt 3p5 GeV'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/217 EcalRecHitsTask Endcap RecSimHit Ratio gt 3p5 GeV',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio gt 3p5 GeV'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/218 EcalRecHitsTask Barrel Unc RecSimHit Ratio gt 3p5 GeV',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel Unc RecSimHit Ratio gt 3p5 GeV'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/219 EcalRecHitsTask Endcap Unc RecSimHit Ratio gt 3p5 GeV',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap Unc RecSimHit Ratio gt 3p5 GeV'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/220 EB Occupancy',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Occupancy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/221 EB Amplitude',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Amplitude'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/222 EB Pedestal',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Pedestal'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/223 EB Jitter',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Jitter'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/224 EB Chi2',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Chi2'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/225 EB RecHit Max Sample Ratio',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB RecHit Max Sample Ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/226 EB Occupancy gt 100 adc counts',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Occupancy gt 100 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/227 EB Amplitude gt 100 adc counts',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Amplitude gt 100 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/228 EB Pedestal gt 100 adc counts',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Pedestal gt 100 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/229 EB Jitter gt 100 adc counts',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Jitter gt 100 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/230 EB Chi2 gt 100 adc counts',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Chi2 gt 100 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/231 EB RecHit Max Sample Ratio gt 100 adc counts',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB RecHit Max Sample Ratio gt 100 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/232 EB Amplitude Full Map',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Amplitude Full Map'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/233 EB Pedestal Full Map',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Pedestal Full Map'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/234 EE+ Occupancy',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE+ Occupancy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/235 EE- Occupancy',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE- Occupancy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/236 EE Amplitude',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Amplitude'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/237 EE Pedestal',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Pedestal'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/238 EE Jitter',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Jitter'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/239 EE Chi2',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Chi2'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/240 EE RecHit Max Sample Ratio',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE RecHit Max Sample Ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/241 EE+ Occupancy gt 60 adc counts',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE+ Occupancy gt 60 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/242 EE- Occupancy gt 60 adc counts',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE- Occupancy gt 60 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/243 EE Amplitude gt 60 adc counts',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Amplitude gt 60 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/244 EE Pedestal gt 60 adc counts',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Pedestal gt 60 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/245 EE Jitter gt 60 adc counts',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Jitter gt 60 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/246 EE Chi2 gt 60 adc counts',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Chi2 gt 60 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/247 EE RecHit Max Sample Ratio gt 60 adc counts',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE RecHit Max Sample Ratio gt 60 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/248 EE Amplitude Full Map',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Amplitude Full Map'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/249 EE Pedestal Full Map',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Pedestal Full Map'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/250 ES Energy',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/251 ES Energy Plane1 Side+',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Energy Plane1 Side+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/252 ES Energy Plane2 Side+',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Energy Plane2 Side+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/253 ES Energy Plane1 Side-',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Energy Plane1 Side-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/254 ES Energy Plane2 Side-',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Energy Plane2 Side-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/255 ES Multiplicity',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/256 ES Multiplicity Plane1 Side+',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Multiplicity Plane1 Side+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/257 ES Multiplicity Plane2 Side+',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Multiplicity Plane2 Side+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/258 ES Multiplicity Plane1 Side-',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Multiplicity Plane1 Side-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/259 ES Multiplicity Plane2 Side-',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Multiplicity Plane2 Side-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/260 Preshower EE vs ES energy Side+',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/Preshower EE vs ES energy Side+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/261 Preshower EE vs ES energy Side-',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/Preshower EE vs ES energy Side-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/262 EcalRecHitsTask Barrel Log10 Energy',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel Log10 Energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/263 EcalRecHitsTask Endcap Log10 Energy',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap Log10 Energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/264 EcalRecHitsTask Preshower Log10 Energy',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Preshower Log10 Energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/265 EcalRecHits Barrel Log10En vs Hit Contribution',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHits Barrel Log10En vs Hit Contribution'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/266 EcalRecHits Barrel Log10En5x5 vs Hit Contribution',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHits Barrel Log10En5x5 vs Hit Contribution'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/267 EcalRecHits Endcap Log10En vs Hit Contribution',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHits Endcap Log10En vs Hit Contribution'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/268 EcalRecHits Endcap Log10En5x5 vs Hit Contribution',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHits Endcap Log10En5x5 vs Hit Contribution'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/269 EcalRecHits Preshower Log10En vs Hit Contribution',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHits Preshower Log10En vs Hit Contribution'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/270 EB Occupancy Flag=5 6',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EB Occupancy Flag=5 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/271 EB Occupancy Flag=8 9',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EB Occupancy Flag=8 9'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/272 EE+ Occupancy Flag=5 6',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EE+ Occupancy Flag=5 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/273 EE+ Occupancy Flag=8 9',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EE+ Occupancy Flag=8 9'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/274 EE- Occupancy Flag=5 6',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EE- Occupancy Flag=5 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/275 EE- Occupancy Flag=8 9',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EE- Occupancy Flag=8 9'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/276 EcalRecHitsTask Barrel 5x5 RecSimHit Ratio vs SimHit Flag=8',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel 5x5 RecSimHit Ratio vs SimHit Flag=8'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/277 EcalRecHitsTask Barrel RecSimHit Ratio Channel Status=10 11',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio Channel Status=10 11'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/278 EcalRecHitsTask Barrel RecSimHit Ratio Channel Status=12',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio Channel Status=12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/279 EcalRecHitsTask Barrel RecSimHit Ratio Channel Status=13',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio Channel Status=13'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/280 EcalRecHitsTask Barrel RecSimHit Ratio Flag=6',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio Flag=6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/281 EcalRecHitsTask Barrel RecSimHit Ratio Flag=7',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio Flag=7'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/282 EcalRecHitsTask Barrel RecSimHit Ratio vs SimHit Flag=5 6',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio vs SimHit Flag=5 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/283 EcalRecHitsTask Endcap RecSimHit Ratio Channel Status=10 11',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio Channel Status=10 11'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/284 EcalRecHitsTask Endcap RecSimHit Ratio Channel Status=12',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio Channel Status=12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/285 EcalRecHitsTask Endcap RecSimHit Ratio Channel Status=13',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio Channel Status=13'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/286 EcalRecHitsTask Endcap RecSimHit Ratio Flag=6',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio Flag=6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/287 EcalRecHitsTask Endcap RecSimHit Ratio Flag=7',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio Flag=7'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/288 EcalRecHitsTask Endcap RecSimHit Ratio vs SimHit Flag=5 6',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio vs SimHit Flag=5 6'}])
