def ecallayout(i, p, *rows): i[p] = DQMItem(layout=rows)

ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/000 EcalSimHitsValidation Gun Momentum',[{'path': 'EcalHitsV/EcalSimHitsValidation/EcalSimHitsValidation Gun Momentum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/001 EcalSimHitsValidation Gun Eta',[{'path': 'EcalHitsV/EcalSimHitsValidation/EcalSimHitsValidation Gun Eta'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/002 EcalSimHitsValidation Gun Phi',[{'path': 'EcalHitsV/EcalSimHitsValidation/EcalSimHitsValidation Gun Phi'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/003 EcalSimHitsValidation Barrel fraction of energy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EcalSimHitsValidation Barrel fraction of energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/004 EcalSimHitsValidation Endcap fraction of energy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EcalSimHitsValidation Endcap fraction of energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/005 EcalSimHitsValidation Preshower fraction of energy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EcalSimHitsValidation Preshower fraction of energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/006 EB hits multiplicity',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB hits multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/007 EE+ hits multiplicity',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE+ hits multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/008 EE- hits multiplicity',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE- hits multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/009 EB crystals multiplicity',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB crystals multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/010 EE+ crystals multiplicity',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE+ crystals multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/011 EE- crystals multiplicity',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE- crystals multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/012 EB crystal energy spectrum',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB crystal energy spectrum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/013 EB crystal energy spectrum 2',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB crystal energy spectrum 2'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/014 EE crystal energy spectrum',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE crystal energy spectrum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/015 EE crystal energy spectrum 2',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE crystal energy spectrum 2'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/016 EB hits energy spectrum',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB hits energy spectrum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/017 EB hits energy spectrum 2',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB hits energy spectrum 2'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/018 EE hits energy spectrum',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE hits energy spectrum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/019 EE hits energy spectrum 2',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE hits energy spectrum 2'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/020 EB occupancy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB occupancy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/021 EE+ occupancy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE+ occupancy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/022 EE- occupancy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE- occupancy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/023 EB longitudinal shower profile',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB longitudinal shower profile'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/024 EE longitudinal shower profile',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE longitudinal shower profile'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/025 EB E1',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB E1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/026 EB E9',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB E9'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/027 EB E25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB E25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/028 EE E1',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE E1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/029 EE E9',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE E9'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/030 EE E25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE E25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/031 EB E1oE9',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB E1oE9'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/032 EB E1oE25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB E1oE25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/033 EB E9oE25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB E9oE25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/034 EE E1oE9',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE E1oE9'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/035 EE E1oE25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE E1oE25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/036 EE E9oE25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE E9oE25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/037 ES hits layer 1 multiplicity z+',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits layer 1 multiplicity z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/038 ES hits layer 2 multiplicity z+',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits layer 2 multiplicity z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/039 ES hits layer 1 multiplicity z-',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits layer 1 multiplicity z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/040 ES hits layer 2 multiplicity z-',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits layer 2 multiplicity z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/041 ES hits energy layer 1 z+',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits energy layer 1 z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/042 ES hits energy layer 2 z+',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits energy layer 2 z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/043 ES hits energy layer 1 z-',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits energy layer 1 z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/044 ES hits energy layer 2 z-',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits energy layer 2 z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/045 ES E1+07E2 z+',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES E1+07E2 z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/046 ES E1+07E2 z-',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES E1+07E2 z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/047 ES ene2oEne1 z+',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES ene2oEne1 z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/048 ES ene2oEne1 z-',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES ene2oEne1 z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/049 EE vs ES z+',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE vs ES z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/050 EE vs ES z-',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE vs ES z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/051 EB hits log10energy spectrum',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB hits log10energy spectrum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/052 EB hits log10energy spectrum vs normalized energy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB hits log10energy spectrum vs normalized energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/053 EB hits log10energy spectrum vs normalized energy25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EB hits log10energy spectrum vs normalized energy25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/054 EE hits log10energy spectrum',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE hits log10energy spectrum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/055 EE hits log10energy spectrum vs normalized energy',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE hits log10energy spectrum vs normalized energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/056 EE hits log10energy spectrum vs normalized energy25',[{'path': 'EcalHitsV/EcalSimHitsValidation/EE hits log10energy spectrum vs normalized energy25'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/057 ES hits log10energy spectrum',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits log10energy spectrum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Hits/058 ES hits log10energy spectrum vs normalized energy',[{'path': 'EcalHitsV/EcalSimHitsValidation/ES hits log10energy spectrum vs normalized energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/000 EcalDigiTask Gun Momentum',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Gun Momentum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/001 EcalDigiTask Gun Eta',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Gun Eta'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/002 EcalDigiTask Gun Phi',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Gun Phi'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/003 EcalDigiTask Barrel occupancy',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel occupancy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/004 EcalDigiTask Endcap occupancy z+',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap occupancy z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/005 EcalDigiTask Endcap occupancy z-',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap occupancy z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/006 EcalDigiTask Barrel digis multiplicity',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel digis multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/007 EcalDigiTask Preshower digis multiplicity',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Preshower digis multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/008 EcalDigiTask Endcap multiplicity z+',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap multiplicity z+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/009 EcalDigiTask Endcap multiplicity z-',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap multiplicity z-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/010 EcalDigiTask Barrel global pulse shape',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel global pulse shape'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/011 EcalDigiTask Endcap global pulse shape',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap global pulse shape'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/012 EcalDigiTask Barrel maximum Digi over Sim ratio',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel maximum Digi over Sim ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/013 EcalDigiTask Endcap maximum Digi over Sim ratio',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap maximum Digi over Sim ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/014 EcalDigiTask Barrel maximum Digi over Sim ratio gt 10 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel maximum Digi over Sim ratio gt 10 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/015 EcalDigiTask Endcap maximum Digi over Sim ratio gt 20 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap maximum Digi over Sim ratio gt 20 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/016 EcalDigiTask Barrel maximum Digi over Sim ratio gt 100 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel maximum Digi over Sim ratio gt 100 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/017 EcalDigiTask Endcap maximum Digi over Sim ratio gt 100 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap maximum Digi over Sim ratio gt 100 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/018 EcalDigiTask Barrel ADC counts after gain switch',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC counts after gain switch'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/019 EcalDigiTask Endcap ADC counts after gain switch',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC counts after gain switch'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/020 EcalDigiTask Barrel pedestal for pre-sample',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel pedestal for pre-sample'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/021 EcalDigiTask Endcap pedestal for pre-sample',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap pedestal for pre-sample'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/022 EcalDigiTask Barrel maximum position gt 100 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel maximum position gt 100 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/023 EcalDigiTask Endcap maximum position gt 100 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap maximum position gt 100 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/024 EcalDigiTask Barrel maximum position gt 10 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel maximum position gt 10 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/025 EcalDigiTask Endcap maximum position gt 20 ADC',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap maximum position gt 20 ADC'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/026 EcalDigiTask Preshower ADC pulse 01',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Preshower ADC pulse 01'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/027 EcalDigiTask Preshower ADC pulse 02',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Preshower ADC pulse 02'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/028 EcalDigiTask Preshower ADC pulse 03',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Preshower ADC pulse 03'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/029 EcalDigiTask Barrel analog pulse 01',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 01'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/030 EcalDigiTask Barrel analog pulse 02',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 02'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/031 EcalDigiTask Barrel analog pulse 03',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 03'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/032 EcalDigiTask Barrel analog pulse 04',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 04'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/033 EcalDigiTask Barrel analog pulse 05',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 05'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/034 EcalDigiTask Barrel analog pulse 06',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 06'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/035 EcalDigiTask Barrel analog pulse 07',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 07'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/036 EcalDigiTask Barrel analog pulse 08',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 08'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/037 EcalDigiTask Barrel analog pulse 09',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 09'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/038 EcalDigiTask Barrel analog pulse 10',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel analog pulse 10'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/039 EcalDigiTask Barrel ADC pulse 01 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 01 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/040 EcalDigiTask Barrel ADC pulse 02 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 02 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/041 EcalDigiTask Barrel ADC pulse 03 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 03 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/042 EcalDigiTask Barrel ADC pulse 04 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 04 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/043 EcalDigiTask Barrel ADC pulse 05 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 05 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/044 EcalDigiTask Barrel ADC pulse 06 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 06 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/045 EcalDigiTask Barrel ADC pulse 07 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 07 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/046 EcalDigiTask Barrel ADC pulse 08 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 08 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/047 EcalDigiTask Barrel ADC pulse 09 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 09 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/048 EcalDigiTask Barrel ADC pulse 10 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 10 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/049 EcalDigiTask Barrel ADC pulse 01 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 01 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/050 EcalDigiTask Barrel ADC pulse 02 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 02 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/051 EcalDigiTask Barrel ADC pulse 03 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 03 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/052 EcalDigiTask Barrel ADC pulse 04 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 04 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/053 EcalDigiTask Barrel ADC pulse 05 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 05 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/054 EcalDigiTask Barrel ADC pulse 06 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 06 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/055 EcalDigiTask Barrel ADC pulse 07 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 07 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/056 EcalDigiTask Barrel ADC pulse 08 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 08 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/057 EcalDigiTask Barrel ADC pulse 09 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 09 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/058 EcalDigiTask Barrel ADC pulse 10 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 10 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/059 EcalDigiTask Barrel ADC pulse 01 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 01 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/060 EcalDigiTask Barrel ADC pulse 02 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 02 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/061 EcalDigiTask Barrel ADC pulse 03 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 03 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/062 EcalDigiTask Barrel ADC pulse 04 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 04 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/063 EcalDigiTask Barrel ADC pulse 05 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 05 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/064 EcalDigiTask Barrel ADC pulse 06 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 06 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/065 EcalDigiTask Barrel ADC pulse 07 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 07 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/066 EcalDigiTask Barrel ADC pulse 08 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 08 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/067 EcalDigiTask Barrel ADC pulse 09 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 09 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/068 EcalDigiTask Barrel ADC pulse 10 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 10 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/069 EcalDigiTask Barrel ADC pulse 01 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 01 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/070 EcalDigiTask Barrel ADC pulse 02 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 02 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/071 EcalDigiTask Barrel ADC pulse 03 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 03 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/072 EcalDigiTask Barrel ADC pulse 04 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 04 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/073 EcalDigiTask Barrel ADC pulse 05 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 05 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/074 EcalDigiTask Barrel ADC pulse 06 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 06 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/075 EcalDigiTask Barrel ADC pulse 07 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 07 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/076 EcalDigiTask Barrel ADC pulse 08 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 08 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/077 EcalDigiTask Barrel ADC pulse 09 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 09 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/078 EcalDigiTask Barrel ADC pulse 10 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel ADC pulse 10 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/079 EcalDigiTask Barrel gain pulse 01',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 01'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/080 EcalDigiTask Barrel gain pulse 02',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 02'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/081 EcalDigiTask Barrel gain pulse 03',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 03'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/082 EcalDigiTask Barrel gain pulse 04',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 04'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/083 EcalDigiTask Barrel gain pulse 05',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 05'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/084 EcalDigiTask Barrel gain pulse 06',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 06'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/085 EcalDigiTask Barrel gain pulse 07',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 07'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/086 EcalDigiTask Barrel gain pulse 08',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 08'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/087 EcalDigiTask Barrel gain pulse 09',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 09'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/088 EcalDigiTask Barrel gain pulse 10',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Barrel gain pulse 10'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/089 EcalDigiTask Endcap analog pulse 01',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 01'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/090 EcalDigiTask Endcap analog pulse 02',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 02'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/091 EcalDigiTask Endcap analog pulse 03',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 03'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/092 EcalDigiTask Endcap analog pulse 04',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 04'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/093 EcalDigiTask Endcap analog pulse 05',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 05'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/094 EcalDigiTask Endcap analog pulse 06',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 06'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/095 EcalDigiTask Endcap analog pulse 07',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 07'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/096 EcalDigiTask Endcap analog pulse 08',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 08'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/097 EcalDigiTask Endcap analog pulse 09',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 09'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/098 EcalDigiTask Endcap analog pulse 10',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap analog pulse 10'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/099 EcalDigiTask Endcap ADC pulse 01 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 01 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/100 EcalDigiTask Endcap ADC pulse 02 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 02 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/101 EcalDigiTask Endcap ADC pulse 03 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 03 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/102 EcalDigiTask Endcap ADC pulse 04 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 04 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/103 EcalDigiTask Endcap ADC pulse 05 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 05 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/104 EcalDigiTask Endcap ADC pulse 06 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 06 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/105 EcalDigiTask Endcap ADC pulse 07 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 07 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/106 EcalDigiTask Endcap ADC pulse 08 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 08 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/107 EcalDigiTask Endcap ADC pulse 09 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 09 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/108 EcalDigiTask Endcap ADC pulse 10 Gain 0 - Saturated',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 10 Gain 0 - Saturated'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/109 EcalDigiTask Endcap ADC pulse 01 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 01 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/110 EcalDigiTask Endcap ADC pulse 02 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 02 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/111 EcalDigiTask Endcap ADC pulse 03 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 03 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/112 EcalDigiTask Endcap ADC pulse 04 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 04 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/113 EcalDigiTask Endcap ADC pulse 05 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 05 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/114 EcalDigiTask Endcap ADC pulse 06 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 06 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/115 EcalDigiTask Endcap ADC pulse 07 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 07 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/116 EcalDigiTask Endcap ADC pulse 08 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 08 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/117 EcalDigiTask Endcap ADC pulse 09 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 09 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/118 EcalDigiTask Endcap ADC pulse 10 Gain 1',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 10 Gain 1'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/119 EcalDigiTask Endcap ADC pulse 01 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 01 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/120 EcalDigiTask Endcap ADC pulse 02 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 02 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/121 EcalDigiTask Endcap ADC pulse 03 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 03 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/122 EcalDigiTask Endcap ADC pulse 04 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 04 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/123 EcalDigiTask Endcap ADC pulse 05 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 05 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/124 EcalDigiTask Endcap ADC pulse 06 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 06 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/125 EcalDigiTask Endcap ADC pulse 07 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 07 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/126 EcalDigiTask Endcap ADC pulse 08 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 08 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/127 EcalDigiTask Endcap ADC pulse 09 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 09 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/128 EcalDigiTask Endcap ADC pulse 10 Gain 6',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 10 Gain 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/129 EcalDigiTask Endcap ADC pulse 01 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 01 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/130 EcalDigiTask Endcap ADC pulse 02 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 02 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/131 EcalDigiTask Endcap ADC pulse 03 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 03 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/132 EcalDigiTask Endcap ADC pulse 04 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 04 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/133 EcalDigiTask Endcap ADC pulse 05 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 05 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/134 EcalDigiTask Endcap ADC pulse 06 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 06 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/135 EcalDigiTask Endcap ADC pulse 07 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 07 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/136 EcalDigiTask Endcap ADC pulse 08 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 08 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/137 EcalDigiTask Endcap ADC pulse 09 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 09 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/138 EcalDigiTask Endcap ADC pulse 10 Gain 12',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap ADC pulse 10 Gain 12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/139 EcalDigiTask Endcap gain pulse 01',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 01'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/140 EcalDigiTask Endcap gain pulse 02',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 02'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/141 EcalDigiTask Endcap gain pulse 03',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 03'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/142 EcalDigiTask Endcap gain pulse 04',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 04'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/143 EcalDigiTask Endcap gain pulse 05',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 05'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/144 EcalDigiTask Endcap gain pulse 06',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 06'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/145 EcalDigiTask Endcap gain pulse 07',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 07'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/146 EcalDigiTask Endcap gain pulse 08',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 08'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/147 EcalDigiTask Endcap gain pulse 09',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 09'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/Digis/148 EcalDigiTask Endcap gain pulse 10',[{'path': 'EcalDigisV/EcalDigiTask/EcalDigiTask Endcap gain pulse 10'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/000 EcalRecHitsTask Gun Momentum',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Gun Momentum'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/001 EcalRecHitsTask Gun Eta',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Gun Eta'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/002 EcalRecHitsTask Gun Phi',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Gun Phi'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/003 EcalRecHitsTask Barrel RecSimHit Ratio',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/004 EcalRecHitsTask Endcap RecSimHit Ratio',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/005 EcalRecHitsTask Preshower RecSimHit Ratio',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Preshower RecSimHit Ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/006 EcalRecHitsTask Barrel Unc RecSimHit Ratio',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel Unc RecSimHit Ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/007 EcalRecHitsTask Endcap Unc RecSimHit Ratio',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap Unc RecSimHit Ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/008 EcalRecHitsTask Barrel RecSimHit Ratio gt 3p5 GeV',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio gt 3p5 GeV'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/009 EcalRecHitsTask Endcap RecSimHit Ratio gt 3p5 GeV',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio gt 3p5 GeV'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/010 EcalRecHitsTask Barrel Unc RecSimHit Ratio gt 3p5 GeV',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel Unc RecSimHit Ratio gt 3p5 GeV'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/011 EcalRecHitsTask Endcap Unc RecSimHit Ratio gt 3p5 GeV',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap Unc RecSimHit Ratio gt 3p5 GeV'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/012 EB Occupancy',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Occupancy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/013 EB Amplitude',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Amplitude'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/014 EB Pedestal',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Pedestal'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/015 EB Jitter',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Jitter'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/016 EB Chi2',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Chi2'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/017 EB RecHit Max Sample Ratio',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB RecHit Max Sample Ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/018 EB Occupancy gt 100 adc counts',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Occupancy gt 100 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/019 EB Amplitude gt 100 adc counts',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Amplitude gt 100 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/020 EB Pedestal gt 100 adc counts',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Pedestal gt 100 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/021 EB Jitter gt 100 adc counts',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Jitter gt 100 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/022 EB Chi2 gt 100 adc counts',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Chi2 gt 100 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/023 EB RecHit Max Sample Ratio gt 100 adc counts',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB RecHit Max Sample Ratio gt 100 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/024 EB Amplitude Full Map',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Amplitude Full Map'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/025 EB Pedestal Full Map',[{'path': 'EcalRecHitsV/EcalBarrelRecHitsTask/EB Pedestal Full Map'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/026 EE+ Occupancy',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE+ Occupancy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/027 EE- Occupancy',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE- Occupancy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/028 EE Amplitude',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Amplitude'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/029 EE Pedestal',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Pedestal'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/030 EE Jitter',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Jitter'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/031 EE Chi2',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Chi2'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/032 EE RecHit Max Sample Ratio',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE RecHit Max Sample Ratio'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/033 EE+ Occupancy gt 60 adc counts',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE+ Occupancy gt 60 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/034 EE- Occupancy gt 60 adc counts',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE- Occupancy gt 60 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/035 EE Amplitude gt 60 adc counts',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Amplitude gt 60 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/036 EE Pedestal gt 60 adc counts',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Pedestal gt 60 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/037 EE Jitter gt 60 adc counts',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Jitter gt 60 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/038 EE Chi2 gt 60 adc counts',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Chi2 gt 60 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/039 EE RecHit Max Sample Ratio gt 60 adc counts',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE RecHit Max Sample Ratio gt 60 adc counts'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/040 EE Amplitude Full Map',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Amplitude Full Map'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/041 EE Pedestal Full Map',[{'path': 'EcalRecHitsV/EcalEndcapRecHitsTask/EE Pedestal Full Map'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/042 ES Energy',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/043 ES Energy Plane1 Side+',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Energy Plane1 Side+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/044 ES Energy Plane2 Side+',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Energy Plane2 Side+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/045 ES Energy Plane1 Side-',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Energy Plane1 Side-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/046 ES Energy Plane2 Side-',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Energy Plane2 Side-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/047 ES Multiplicity',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Multiplicity'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/048 ES Multiplicity Plane1 Side+',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Multiplicity Plane1 Side+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/049 ES Multiplicity Plane2 Side+',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Multiplicity Plane2 Side+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/050 ES Multiplicity Plane1 Side-',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Multiplicity Plane1 Side-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/051 ES Multiplicity Plane2 Side-',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/ES Multiplicity Plane2 Side-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/052 Preshower EE vs ES energy Side+',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/Preshower EE vs ES energy Side+'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/053 Preshower EE vs ES energy Side-',[{'path': 'EcalRecHitsV/EcalPreshowerRecHitsTask/Preshower EE vs ES energy Side-'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/054 EcalRecHitsTask Barrel Log10 Energy',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel Log10 Energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/055 EcalRecHitsTask Endcap Log10 Energy',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap Log10 Energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/056 EcalRecHitsTask Preshower Log10 Energy',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Preshower Log10 Energy'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/057 EcalRecHits Barrel Log10En vs Hit Contribution',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHits Barrel Log10En vs Hit Contribution'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/058 EcalRecHits Barrel Log10En5x5 vs Hit Contribution',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHits Barrel Log10En5x5 vs Hit Contribution'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/059 EcalRecHits Endcap Log10En vs Hit Contribution',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHits Endcap Log10En vs Hit Contribution'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/060 EcalRecHits Endcap Log10En5x5 vs Hit Contribution',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHits Endcap Log10En5x5 vs Hit Contribution'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/061 EcalRecHits Preshower Log10En vs Hit Contribution',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHits Preshower Log10En vs Hit Contribution'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/062 EB Occupancy Flag=5 6',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EB Occupancy Flag=5 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/063 EB Occupancy Flag=8 9',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EB Occupancy Flag=8 9'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/064 EE+ Occupancy Flag=5 6',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EE+ Occupancy Flag=5 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/065 EE+ Occupancy Flag=8 9',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EE+ Occupancy Flag=8 9'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/066 EE- Occupancy Flag=5 6',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EE- Occupancy Flag=5 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/067 EE- Occupancy Flag=8 9',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EE- Occupancy Flag=8 9'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/068 EcalRecHitsTask Barrel 5x5 RecSimHit Ratio vs SimHit Flag=8',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel 5x5 RecSimHit Ratio vs SimHit Flag=8'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/069 EcalRecHitsTask Barrel RecSimHit Ratio Channel Status=10 11',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio Channel Status=10 11'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/070 EcalRecHitsTask Barrel RecSimHit Ratio Channel Status=12',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio Channel Status=12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/071 EcalRecHitsTask Barrel RecSimHit Ratio Channel Status=13',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio Channel Status=13'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/072 EcalRecHitsTask Barrel RecSimHit Ratio Flag=6',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio Flag=6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/073 EcalRecHitsTask Barrel RecSimHit Ratio Flag=7',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio Flag=7'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/074 EcalRecHitsTask Barrel RecSimHit Ratio vs SimHit Flag=5 6',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Barrel RecSimHit Ratio vs SimHit Flag=5 6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/075 EcalRecHitsTask Endcap RecSimHit Ratio Channel Status=10 11',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio Channel Status=10 11'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/076 EcalRecHitsTask Endcap RecSimHit Ratio Channel Status=12',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio Channel Status=12'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/077 EcalRecHitsTask Endcap RecSimHit Ratio Channel Status=13',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio Channel Status=13'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/078 EcalRecHitsTask Endcap RecSimHit Ratio Flag=6',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio Flag=6'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/079 EcalRecHitsTask Endcap RecSimHit Ratio Flag=7',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio Flag=7'}])
ecallayout(dqmitems, 'MCLayouts/Ecal/RecHits/080 EcalRecHitsTask Endcap RecSimHit Ratio vs SimHit Flag=5 6',[{'path': 'EcalRecHitsV/EcalRecHitsTask/EcalRecHitsTask Endcap RecSimHit Ratio vs SimHit Flag=5 6'}])
