def pixellayout(i, p, *rows): i["PixelPhase1/Layouts/" + p] = DQMItem(layout=rows)
pixellayout(dqmitems, "00a - ReportSummary: Layer or Disk vs subdet",
   [{ 'path': "PixelPhase1/EventInfo/reportSummaryMap",
      'description': "Summary results of quality tests: Layer/Disk (y-axis) vs. Subdetectors (x-axis). See the PixelPhase1/EventInfo directory for more details.",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}]
   )
pixellayout(dqmitems, "00b - FED Occupancy vs Lumi Block",
   [{ 'path': "PixelPhase1/num_feddigistrend_per_LumiBlock_per_FED",
      'description': "Profile of number of digis per Event and FED by LumiBlock by FED (Z:#digis)",
      'draw': { 'withref': "no" }}]
   )
pixellayout(dqmitems, "00c - Error per Type per FED Summary",
   [{ 'path': "PixelPhase1/FED/nerrors_per_type_per_FED",
      'description': "Number of Errors of each type per FED. Channel 0 is assigned for errors where the channel number is not known.",
      'draw': { 'withref': "no" }}]
   )
pixellayout(dqmitems, "00d - Error per Link in FED per FED Summary",
   [{ 'path': "PixelPhase1/FED/errors_per_LinkInFed_per_FED",
      'description': "Total number of errors in a map of FED channels (y-axis) vs. FED (x-axis). Channel 0 is assigned for errors where the channel number is not known.",
      'draw': { 'withref': "no" }}]
   )
pixellayout(dqmitems, "00e - Event Rate",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/eventrate_per_BX",
      'description': "Event rate per bunch crossing",
      'draw': { 'withref': "no" }}]
   )

pixellayout(dqmitems, "01a - Cluster Size vs Cluster Eta",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/sizeyvseta_PXBarrel",
      'description': "Cluster size along the beamline in pixel length (y-axis) vs the cluster eta position in eta (x-axis)",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}]
   )

pixellayout(dqmitems, "01b - Cluster Size vs Cluster Eta in PXLayers",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/sizeyvseta_PXLayer_1",
      'description': "Cluster size along the beamline in pixel length (y-axis) vs the cluster eta position in eta (x-axis) in layer 1 of pixel barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ"}},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/sizeyvseta_PXLayer_2",
      'description': "Cluster size along the beamline in pixel length (y-axis) vs the cluster eta position in eta (x-axis) in layer 2 of pixel barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/sizeyvseta_PXLayer_3",
      'description': "Cluster size along the beamline in pixel length (y-axis) vs the cluster eta position in eta (x-axis) in layer 3 of pixel barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/sizeyvseta_PXLayer_4",
      'description': "Cluster size along the beamline in pixel length (y-axis) vs the cluster eta position in eta (x-axis) in layer 4 of pixel barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   )

pixellayout(dqmitems, "02a - Cluster Position: Z vs Phi summary",
   [{'path': "PixelPhase1/Phase1_MechanicalView/clusterposition_zphi",
     'description': "Cluster position in global coordinates by Global Phi (y-axis) vs Global Z (x-axis)",
     'draw': { 'withref': "no", 'drawopts': "COLZ" }}]
   )

pixellayout(dqmitems, "02b - Cluster Position: Z vs Phi PXLayers summary",
   [{'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/clusterposition_zphi_PXLayer_1",
     'description': "Cluster position in global coordinates by Global Phi (y-axis) vs Global Z (x-axis) in layer 1 of barrel",
     'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    {'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/clusterposition_zphi_PXLayer_2",
     'description': "Cluster position in global coordinates by Global Phi (y-axis) vs Global Z (x-axis) in layer 2 of barrel",
     'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   [{'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/clusterposition_zphi_PXLayer_3",
     'description': "Cluster position in global coordinates by Global Phi (y-axis) vs Global Z (x-axis) in layer 3 of barrel",
     'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    {'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/clusterposition_zphi_PXLayer_4",
     'description': "Cluster position in global coordinates by Global Phi (y-axis) vs Global Z (x-axis) in layer 4 of barrel",
     'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   )

pixellayout(dqmitems, "02c - Cluster Position: X vs Y PXDisks summary",
   [{'path': "PixelPhase1/Phase1_MechanicalView/PXForward/clusterposition_xy_PXDisk_+1",
     'description': "Cluster position in global coordinates by Global Y (y-axis) vs Global X (x-axis) in disk +1 of forward",
     'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    {'path': "PixelPhase1/Phase1_MechanicalView/PXForward/clusterposition_xy_PXDisk_+2",
     'description': "Cluster position in global coordinates by Global Y (y-axis) vs Global X (x-axis) in disk +2 of forward",
     'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    {'path': "PixelPhase1/Phase1_MechanicalView/PXForward/clusterposition_xy_PXDisk_+3",
     'description': "Cluster position in global coordinates by Global Y (y-axis) vs Global X (x-axis) in disk +3 of forward",
     'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   [{'path': "PixelPhase1/Phase1_MechanicalView/PXForward/clusterposition_xy_PXDisk_-1",
     'description': "Cluster position in global coordinates by Global Y (y-axis) vs Global X (x-axis) in disk -1 of forward",
     'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    {'path': "PixelPhase1/Phase1_MechanicalView/PXForward/clusterposition_xy_PXDisk_-2",
     'description': "Cluster position in global coordinates by Global Y (y-axis) vs Global X (x-axis) in disk -2 of forward",
     'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    {'path': "PixelPhase1/Phase1_MechanicalView/PXForward/clusterposition_xy_PXDisk_-3",
     'description': "Cluster position in global coordinates by Global Y (y-axis) vs Global X (x-axis) in disk -3 of forward",
     'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   )

#pixellayout(dqmitems, "03 - PixelPhase1 Dead ROC trends",
#   [{ 'path': "PixelPhase1/deadRocTrendBPix",
#      'description': "Disabled ROC trend summary in PXBarrel",
#      'draw': { 'withref': "no" }},
#    { 'path': "PixelPhase1/deadRocTrendFPix",
#      'description': "Disabled ROC trend summary in PXForward",
#      'draw': { 'withref': "no" }}],
#   )

pixellayout(dqmitems, "03 - Dead ROC trends in PXLayers and PXRings",
   [{ 'path': "PixelPhase1/deadRocTrendLayer_1",
      'description': "Disabled ROC trend summary in PXLayer 1",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/deadRocTrendLayer_2",
      'description': "Disabled ROC trend summary in PXLayer 2",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/deadRocTrendLayer_3",
      'description': "Disabled ROC trend summary in PXLayer 3",
      'draw': { 'withref': "no" }}],
   [{ 'path': "PixelPhase1/deadRocTrendLayer_4",
      'description': "Disabled ROC trend summary in PXLayer 4",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/deadRocTrendRing_1",
      'description': "Disabled ROC trend summary in PXRing 1",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/deadRocTrendRing_2",
      'description': "Disabled ROC trend summary in PXRing 2",
      'draw': { 'withref': "no" }}],
   )
   
pixellayout(dqmitems, "04a - OnTrack Cluster Charge",
  [{ 'path': "TrackTimingPixelPhase1/Phase1_Track/charge_PXBarrel",
     'description': "charge PXBarrel",
     'draw': {'withref' : "no"}},
   { 'path': "TrackTimingPixelPhase1/Phase1_Track/charge_PXForward",
     'description': "charge PXForward",
     'draw': {'withref' : "no"}}],
  )

pixellayout(dqmitems, "04b - OnTrack Cluster Charge in PXLayers",
   [{ 'path': "TrackTimingPixelPhase1/Phase1_Track/PXBarrel/charge_PXLayer_1",
      'description': "Cluster (onTrack) charge in layer 1 of pixel barrel",
      'draw': { 'withref': "no" }},
    { 'path': "TrackTimingPixelPhase1/Phase1_Track/PXBarrel/charge_PXLayer_2",
      'description': "Cluster (onTrack) charge in layer 2 of pixel barrel",
      'draw': { 'withref': "no" }}],
   [{ 'path': "TrackTimingPixelPhase1/Phase1_Track/PXBarrel/charge_PXLayer_3",
      'description': "Cluster (onTrack) charge in layer 3 of pixel barrel",
      'draw': { 'withref': "no" }},
    { 'path': "TrackTimingPixelPhase1/Phase1_Track/PXBarrel/charge_PXLayer_4",
      'description': "Cluster (onTrack) charge in layer 4 of pixel barrel",
      'draw': { 'withref': "no" }}],
  )

pixellayout(dqmitems, "04c - OnTrack Cluster Charge PXDisks",
   [{ 'path': "TrackTimingPixelPhase1/Phase1_Track/PXForward/charge_PXDisk_+1",
      'description': "Cluster (onTrack) charge in disk +1 of pixel forward",
      'draw': { 'withref': "no" }},
    { 'path': "TrackTimingPixelPhase1/Phase1_Track/PXForward/charge_PXDisk_+2",
      'description': "Cluster (onTrack) charge in disk +2 of pixel forward",
      'draw': { 'withref': "no" }},
    { 'path': "TrackTimingPixelPhase1/Phase1_Track/PXForward/charge_PXDisk_+3",
      'description': "Cluster (onTrack) charge in disk +3 of pixel forward",
      'draw': { 'withref': "no" }}],
   [{ 'path': "TrackTimingPixelPhase1/Phase1_Track/PXForward/charge_PXDisk_-1",
      'description': "Cluster (onTrack) charge in disk -1 of pixel forward",
      'draw': { 'withref': "no" }},
    { 'path': "TrackTimingPixelPhase1/Phase1_Track/PXForward/charge_PXDisk_-2",
      'description': "Cluster (onTrack) charge in disk -2 of pixel forward",
      'draw': { 'withref': "no" }},
    { 'path': "TrackTimingPixelPhase1/Phase1_Track/PXForward/charge_PXDisk_-3",
      'description': "Cluster (onTrack) charge in disk -3 of pixel forward",
      'draw': { 'withref': "no" }}],
   )
   
pixellayout(dqmitems, "05a - Cluster Size Summary",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/size_PXBarrel",
      'description': "Total cluster size in the barrel modules",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/size_PXForward",
      'description': "Total cluster size in the Endcap modules",
      'draw': { 'withref': "no" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/size_per_Lumisection_PXBarrel",
      'description': "Mean cluster size per lumisection in barrel",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/size_per_Lumisection_PXForward",
      'description': "Mean cluster size per lumisection in barrel",
      'draw': { 'withref': "no" }}]
   )

pixellayout(dqmitems, "05b - Cluster Size in PXLayers",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/size_PXLayer_1",
      'description': "Total cluster size in layer 1 of pixel barrel",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/size_PXLayer_2",
      'description': "Total cluster size in layer 2 of pixel barrel",
      'draw': { 'withref': "no" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/size_PXLayer_3",
      'description': "Total cluster size in layer 3 of pixel barrel",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/size_PXLayer_4",
      'description': "Total cluster size in layer 4 of pixel barrel",
      'draw': { 'withref': "no" }}],
   )

pixellayout(dqmitems, "05c - Cluster Size in PXDisks",
   [{'path': "PixelPhase1/Phase1_MechanicalView/PXForward/size_PXDisk_+1",
     'description': "Total cluster size in disk +1 of pixel forward",
     'draw': { 'withref': "no" }},
    {'path': "PixelPhase1/Phase1_MechanicalView/PXForward/size_PXDisk_+2",
     'description': "Total cluster size in disk +2 of pixel forward",
     'draw': { 'withref': "no" }},
    {'path': "PixelPhase1/Phase1_MechanicalView/PXForward/size_PXDisk_+3",
     'description': "Total cluster size in disk +3 of pixel forward",
     'draw': { 'withref': "no" }}],
   [{'path': "PixelPhase1/Phase1_MechanicalView/PXForward/size_PXDisk_-1",
     'description': "Total cluster size in disk -1 of pixel forward",
     'draw': { 'withref': "no" }},
    {'path': "PixelPhase1/Phase1_MechanicalView/PXForward/size_PXDisk_-2",
     'description': "Total cluster size in disk -2 of pixel forward",
     'draw': { 'withref': "no" }},
    {'path': "PixelPhase1/Phase1_MechanicalView/PXForward/size_PXDisk_-3",
     'description': "Total cluster size in disk -3 of pixel forward",
     'draw': { 'withref': "no" }}],
   )

pixellayout(dqmitems, "06a - Num Clusters Summary",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/num_clusters_PXBarrel",
      'description': "Number of clusters per event in barrel",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/num_clusters_PXForward",
      'description': "Number of clusters per event in forward",
      'draw': { 'withref': "no" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/num_clusters_per_Lumisection_PXBarrel",
      'description': "Mean cluster value per lumisection in barrel",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/num_clusters_per_Lumisection_PXForward",
      'description': "Mean cluster value per lumisection in forward",
      'draw': { 'withref': "no" }}]
   )

pixellayout(dqmitems, "06b - Num Clusters PXLayers",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/num_clusters_PXLayer_1",
      'description': "Number of clusters in layer 1 of pixel barrel",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/num_clusters_PXLayer_2",
      'description': "Number of clusters in layer 2 of pixel barrel",
      'draw': { 'withref': "no" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/num_clusters_PXLayer_3",
      'description': "Number of clusters in layer 3 of pixel barrel",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/num_clusters_PXLayer_4",
      'description': "Number of clusters in layer 4 of pixel barrel",
      'draw': { 'withref': "no" }}],
   )

pixellayout(dqmitems, "06c - Num Clusters PXDisks",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/num_clusters_PXDisk_+1",
      'description': "Number of clusters in disk +1 of pixel forward",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/num_clusters_PXDisk_+2",
      'description': "Number of clusters in disk +2 of pixel forward",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/num_clusters_PXDisk_+3",
      'description': "Number of clusters in disk +3 of pixel forward",
      'draw': { 'withref': "no" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/num_clusters_PXDisk_-1",
      'description': "Number of clusters in disk -1 of pixel forward",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/num_clusters_PXDisk_-2",
      'description': "Number of clusters in disk -2 of pixel forward",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/num_clusters_PXDisk_-3",
      'description': "Number of clusters in disk -3 of pixel forward",
      'draw': { 'withref': "no" }}],
   )

pixellayout(dqmitems, "07a - Digi ADC PXBarrel",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/num_digis_PXBarrel",
      'description': "Number of digis per event in PXBarrel",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/adc_PXBarrel",
      'description': "Adc distribution of digis per event per barrel module",
      'draw': { 'withref': "no" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/num_digis_per_Lumisection_PXBarrel",
      'description': "Mean adc value per lumisection",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/adc_per_Lumisection_PXBarrel",
      'description': "Mean adc value per lumisection",
      'draw': { 'withref': "no" }}]
   )

pixellayout(dqmitems, "07b - Digi ADC PXForward",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/num_digis_PXForward",
      'description': "Number of digis per event in Forward",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/adc_PXForward",
      'description': "Adc distribution of digis per event per forward module",
      'draw': { 'withref': "no" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/num_digis_per_Lumisection_PXForward",
      'description': "Mean adc value per lumisection",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/adc_per_Lumisection_PXForward",
      'description': "Mean adc value per lumisection",
      'draw': { 'withref': "no" }}]
   )

pixellayout(dqmitems, "08a - Cluster Charge Summary",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/charge_PXBarrel",
      'description': "Cluster charge in the barrel modules",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/charge_PXForward",
      'description': "Distribution of raw charge for all digis recorded in the Forward modules - dominant peak should be around 90-100 ADC",
      'draw': { 'withref': "no" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/charge_per_Lumisection_PXBarrel",
      'description': "Mean cluster charge per lumisection in barrel",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/charge_per_Lumisection_PXForward",
      'description': "Mean cluster charge per lumisection in forward",
      'draw': { 'withref': "no" }}]
   )

pixellayout(dqmitems, "08b - Cluster Charge in PXLayers",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/charge_PXLayer_1",
      'description': "Cluster charge in layer 1 of pixel barrel",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/charge_PXLayer_2",
      'description': "Cluster charge in layer 2 of pixel barrel",
      'draw': { 'withref': "no" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/charge_PXLayer_3",
      'description': "Cluster charge in layer 3 of pixel barrel",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/charge_PXLayer_4",
      'description': "Cluster charge in layer 4 of pixel barrel",
      'draw': { 'withref': "no" }}],
   )

pixellayout(dqmitems, "08c - Cluster Charge in PXDisks",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/charge_PXDisk_+1",
      'description': "Cluster charge in disk +1 of pixel forward",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/charge_PXDisk_+2",
      'description': "Cluster charge in disk +2 of pixel forward",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/charge_PXDisk_+3",
      'description': "Cluster charge in disk +3 of pixel forward",
      'draw': { 'withref': "no" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/charge_PXDisk_-1",
      'description': "Cluster charge in disk -1 of pixel forward",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/charge_PXDisk_-2",
      'description': "Cluster charge in disk -2 of pixel forward",
      'draw': { 'withref': "no" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/charge_PXDisk_-3",
      'description': "Cluster charge in disk -3 of pixel forward",
      'draw': { 'withref': "no" }}],
   )

pixellayout(dqmitems, "09a - Cluster Size: Ladder vs Module in PXLayers",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/size_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_1",
      'description': "Profile of total cluster size by signed ladder (y-axis) vs signed module (x-axis) in layer 1 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/size_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_2",
      'description': "Profile of total cluster size by signed ladder (y-axis) vs signed module (x-axis) in layer 2 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/size_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_3",
      'description': "Profile of total cluster size by signed ladder (y-axis) vs signed module (x-axis) in layer 3 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/size_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_4",
      'description': "Profile of total cluster size by signed ladder (y-axis) vs signed module (x-axis) in layer 4 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   )

pixellayout(dqmitems, "09b - Cluster Size: BladePannel vs Disk in PXRings",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/size_per_SignedDiskCoord_per_SignedBladePanelCoord_PXRing_1",
      'description': "Profile of total clusters per event by signed blade pannel (y-axis) vs signed disk (x-axis) in ring 1 of forward",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/size_per_SignedDiskCoord_per_SignedBladePanelCoord_PXRing_2",
      'description': "Profile of total clusters per event by signed blade pannel (y-axis) vs signed disk (x-axis) in ring 2 of forward",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   )

pixellayout(dqmitems, "10a - Cluster Occupancy: Ladder vs Module in PXLayers",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/clusters_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_1",
      'description': "Number of clusters per event by signed ladder (y-axis) vs signed module (x-axis) in layer 1 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/clusters_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_2",
      'description': "Number of clusters per event by signed ladder (y-axis) vs signed module (x-axis) in layer 2 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/clusters_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_3",
      'description': "Number of clusters per event by signed ladder (y-axis) vs signed module (x-axis) in layer 3 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/clusters_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_4",
      'description': "Number of clusters per event by signed ladder (y-axis) vs signed module (x-axis) in layer 4 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   )

pixellayout(dqmitems, "10b - Cluster Occupancy: BladePannel vs Disk in PXRings",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/clusters_per_SignedDiskCoord_per_SignedBladePanelCoord_PXRing_1",
      'description': "Number of clusters per event by signed blade pannel (y-axis) vs signed disk (x-axis) in ring 1 of forward",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/clusters_per_SignedDiskCoord_per_SignedBladePanelCoord_PXRing_2",
      'description': "Number of clusters per event by signed blade pannel (y-axis) vs signed disk (x-axis) in ring 2 of forward",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   )

pixellayout(dqmitems, "11a - Digi Occupancy: Ladder vs Module in PXLayers",
  [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/digi_occupancy_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_1",
      'description': "Digi Occupancy by signed ladder (y-axis) vs signed module (x-axis) in layer 1 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
   { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/digi_occupancy_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_2",
      'description': "Digi Occupancy by signed ladder (y-axis) vs signed module (x-axis) in layer 2 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
  [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/digi_occupancy_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_3",
      'description': "Digi Occupancy by signed ladder (y-axis) vs signed module (x-axis) in layer 1 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
   { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/digi_occupancy_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_4",
      'description': "Digi Occupancy by signed ladder (y-axis) vs signed module (x-axis) in layer 2 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
  )

pixellayout(dqmitems, "11b - Digi Occupancy: BladePannel vs Disk in PXRings",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/digi_occupancy_per_SignedDiskCoord_per_SignedBladePanelCoord_PXRing_1",
      'description': "Digi Occupancy by signed blade pannel (y-axis) vs signed disk (x-axis) in ring 1 of forward",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/digi_occupancy_per_SignedDiskCoord_per_SignedBladePanelCoord_PXRing_2",
      'description': "Digi Occupancy by signed blade pannel (y-axis) vs signed disk (x-axis) in ring 2 of forward",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   )

pixellayout(dqmitems, "12a - ADC: Ladder vs Module in PXLayers",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/adc_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_1",
      'description': "Profile of raw charge for all digis by signed ladder (y-axis) vs signed module (x-axis) in layer 1 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/adc_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_2",
      'description': "Profile of raw charge for all digis by signed ladder (y-axis) vs signed module (x-axis) in layer 2 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/adc_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_3",
      'description': "Profile of raw charge for all digis by signed ladder (y-axis) vs signed module (x-axis) in layer 3 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/adc_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_4",
      'description': "Profile of raw charge for all digis by signed ladder (y-axis) vs signed module (x-axis) in layer 4 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   )

pixellayout(dqmitems, "12b - ADC: BladePannel vs Disk in PXRings",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/adc_per_SignedDiskCoord_per_SignedBladePanelCoord_PXRing_1",
      'description': "Profile of raw charge for all digis by signed blade pannel (y-axis) vs signed disk (x-axis) in ring 1 of forward",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/adc_per_SignedDiskCoord_per_SignedBladePanelCoord_PXRing_2",
      'description': "Profile of raw charge for all digis by signed blade pannel (y-axis) vs signed disk (x-axis) in ring 2 of forward",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
    )

pixellayout(dqmitems, "13a - Cluster Charge: Ladder vs Module in PXLayers",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/charge_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_1",
      'description': "Profile of cluster charge per event by signed ladder (y-axis) vs signed module (x-axis) in layer 1 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/charge_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_2",
      'description': "Profile of cluster charge per event by signed ladder (y-axis) vs signed module (x-axis) in layer 2 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/charge_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_3",
      'description': "Profile of cluster charge per event by signed ladder (y-axis) vs signed module (x-axis) in layer 3 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXBarrel/charge_per_SignedModuleCoord_per_SignedLadderCoord_PXLayer_4",
      'description': "Profile of cluster charge per event by signed ladder (y-axis) vs signed module (x-axis) in layer 4 of barrel",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   )

pixellayout(dqmitems, "13b - Cluster Charge: BladePannel vs Disk in PXRings",
   [{ 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/charge_per_SignedDiskCoord_per_SignedBladePanelCoord_PXRing_1",
      'description': "Profile of cluster charge per event by signed blade pannel (y-axis) vs signed disk (x-axis) in ring 1 of forward",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }},
    { 'path': "PixelPhase1/Phase1_MechanicalView/PXForward/charge_per_SignedDiskCoord_per_SignedBladePanelCoord_PXRing_2",
      'description': "Profile of cluster charge per event by signed blade pannel (y-axis) vs signed disk (x-axis) in ring 2 of forward",
      'draw': { 'withref': "no", 'drawopts': "COLZ" }}],
   )
