def shiftjetmetlayout(i, p, *rows): i["00 Shift/JetMET/" + p] = DQMItem(layout=rows)

shiftjetmetlayout(dqmitems, "00 Calo Jet Plots (for collisions)", [{ 'path': "JetMET/Jet/Cleanedak4CaloJets/PtFirst", 'draw': { 'withref': 'yes' }, 'description': "Distribution of Jet Pt for all cleaned jets (event primary vertex requirement, the distribution should be fast falling with no spikes) (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_pt_plots>more</a>)" },
{ 'path': "JetMET/Jet/Cleanedak4CaloJets/Constituents", 'draw': { 'withref': 'yes' }, 'description': "Number of constituents towers in the jet.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_constit_plots>more</a>)" }],
[{ 'path': "JetMET/Jet/Cleanedak4CaloJets/Phi", 'draw': { 'withref': 'yes' }, 'description': "Phi distribution for all jets.  Should be smooth and without spikes (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_phi_plots>more</a>)" },
{ 'path': "JetMET/Jet/Cleanedak4CaloJets/EtaFirst", 'draw': { 'withref': 'yes' }, 'description': "Eta distribution for all jets.  Should be smooth and without spikes (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_summary_plots#jet_eta_plots>more</a>)" }])

shiftjetmetlayout(dqmitems, "01 Calo Jet Plots (for collisions)", [{ 'path': "JetMET/Jet/Cleanedak4CaloJets/HFrac_Barrel", 'draw': { 'withref': 'yes' }, 'description': "Hadronic energy fraction for cleaned jets in Barrel (...) (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_pt_plots>more</a>)" }],
[{ 'path': "JetMET/Jet/Cleanedak4CaloJets/EFrac_Forward", 'draw': { 'withref': 'yes' }, 'description': "EM fraction for cleand jets on HF. (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_phi_plots>more</a>)" }])

shiftjetmetlayout(dqmitems, "02 PF Jet Plots (for collisions)", [{ 'path': "JetMET/Jet/Cleanedak4PFJets/PtFirst", 'draw': { 'withref': 'yes' }, 'description': "Distribution of Jet Pt for all Particle Flow jets (event primary vertex requirement, the distribution should be fast falling with no spikes) (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_pt_plots>more</a>)" },
{ 'path': "JetMET/Jet/Cleanedak4PFJets/Constituents", 'draw': { 'withref': 'yes' }, 'description': "Number of constituents in the jet.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_constit_plots>more</a>)" }],
[{ 'path': "JetMET/Jet/Cleanedak4PFJets/PhiFirst", 'draw': { 'withref': 'yes' }, 'description': "Phi distribution for Particle Flow jets.  Should be smooth and without spikes (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_phi_plots>more</a>)" },
{ 'path': "JetMET/Jet/Cleanedak4PFJets/EtaFirst", 'draw': { 'withref': 'yes' }, 'description': "Eta distribution for Particle Flow jets.  Should be smooth and without spikes (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_summary_plots#jet_eta_plots>more</a>)" }])

shiftjetmetlayout(dqmitems, "03 PF Jet Plots (for collisions)", [{ 'path': "JetMET/Jet/Cleanedak4PFJets/CHFrac_mediumPt_Barrel", 'draw': { 'withref': 'yes' }, 'description': "Charged hadron energy fraction for Particle Flow jets in Barrel (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_pt_plots>more</a>)" }],
[{ 'path': "JetMET/Jet/Cleanedak4PFJets/PhFrac_mediumPt_EndCap", 'draw': { 'withref': 'yes' }, 'description': "Neutral EM energy fraction for Particle Flow jets in EndCap (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_phi_plots>more</a>)" }])

shiftjetmetlayout(dqmitems, "04 Calo MET Plots (for collisions)", [{ 'path': "JetMET/MET/caloMet/Cleaned/MET", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" },
{ 'path': "JetMET/MET/caloMet/Cleaned/METPhi", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }],
[{ 'path': "JetMET/MET/caloMet/Cleaned/MEx", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing Ex distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#mex_plots>more</a>)" },
{ 'path': "JetMET/MET/caloMet/Cleaned/MEy", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing Ey distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#mey_plots>more</a>)" }])

shiftjetmetlayout(dqmitems, "05 Calo MET Plots (for collisions)", [{ 'path': "JetMET/MET/caloMet/Cleaned/SumET", 'draw': { 'withref': 'yes' }, 'description': "The Scaler Sum ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" }],
[{ 'path': "JetMET/MET/caloMet/Cleaned/CaloEmEtFraction", 'draw': { 'withref': 'yes' }, 'description': "The EM fraction of Calorimeter Missing ET.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#mex_plots>more</a>)" }])

shiftjetmetlayout(dqmitems, "06 PF MET Plots (for collisions)", [{ 'path': "JetMET/MET/pfMet/Cleaned/MET", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" },
{ 'path': "JetMET/MET/pfMet/Cleaned/METPhi", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }],
[{ 'path': "JetMET/MET/pfMet/Cleaned/MEx", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing Ex distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#mex_plots>more</a>)" },
{ 'path': "JetMET/MET/pfMet/Cleaned/MEy", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing Ey distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#mey_plots>more</a>)" }])

shiftjetmetlayout(dqmitems, "07 PF MET Plots (for collisions)", [{ 'path': "JetMET/MET/pfMet/Cleaned/SumET", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Scalar Sum ET distribution. There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" }],
[{ 'path': "JetMET/MET/pfMet/Cleaned/MET_logx", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing ET distribution in log(X) scale.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#mex_plots>more</a>)" }])

shiftjetmetlayout(dqmitems, "08 PF candidates maps", [{ 'path': "JetMET/MET/pfMet/Cleaned/gammaBarrel_pt_", 'description': "The neutral EM Et distribution of the PF candidates in Barrel, there should not be any large holes in the plot (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#ct_emet_plots>more</a>)" },
{ 'path': "JetMET/MET/pfMet/Cleaned/h0Barrel_pt_", 'description': "The neutral hasdronic Et distribution of the PF candidates in Barrel, there should not be any large holes in the plot (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#ct_emet_plots>more</a>)" }],
[{ 'path': "JetMET/MET/pfMet/Cleaned/gammaEndcap_pt_", 'description': "The neutral EM Et distribution of the PF candidates in EndCap, there should not be any large holes in the plot (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#ct_hadet>more</a>)" },
{ 'path': "JetMET/MET/pfMet/Cleaned/h0Endcap_pt_", 'description': "The neutral hadronic Et distribution of the PF candidates in EndCap, there should not be any large holes in the plot (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#ct_hadet>more</a>)" }])

shiftjetmetlayout(dqmitems, "09 PF candidates maps", [{ 'path': "JetMET/MET/pfMet/Cleaned/h_pt_", 'description': "The Charged hadron Pt distribution of the PF candidates, there should not be any large holes in the plot (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#ct_emet_plots>more</a>)" }],
[{ 'path': "JetMET/MET/pfMet/Cleaned/IsoPfChHad_TrackPt", 'description': "The track's Pt distribution for the Isolated charged hadronic PF candidates. (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#ct_hadet>more</a>)" }])

def shiftjetmetcosmicslayout(i, p, *rows): i["00 Shift/JetMET/Cosmics/" + p] = DQMItem(layout=rows)

shiftjetmetcosmicslayout(dqmitems, "00 Jet Plots (for cosmics)", [{ 'path': "JetMET/Jet/AntiKtJets/Pt2", 'draw': { 'withref': 'yes' }, 'description': "Distribution of Jet Pt for all cleaned jets (event primary vertex requirement, the distribution should be fast falling with no spikes) (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_pt_plots>more</a>)" },
{ 'path': "JetMET/Jet/AntiKtJets/Eta", 'draw': { 'withref': 'yes' }, 'description': "Eta distribution for all jets.  Should be smooth and without spikes (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_summary_plots#jet_eta_plots>more</a>)" }],
[{ 'path': "JetMET/Jet/AntiKtJets/Phi", 'draw': { 'withref': 'yes' }, 'description': "Phi distribution for all jets.  Should be smooth and without spikes (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_phi_plots>more</a>)" },
{ 'path': "JetMET/Jet/AntiKtJets/Constituents", 'draw': { 'withref': 'yes' }, 'description': "Number of constituents towers in the jet.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_constit_plots>more</a>)" }])

shiftjetmetcosmicslayout(dqmitems, "01 Calo MET Plots (for cosmics)", [{ 'path': "JetMET/MET/CaloMET/All/METTask_CaloMET", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" },
{ 'path': "JetMET/MET/CaloMET/All/METTask_CaloMETPhi", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }],
[{ 'path': "JetMET/MET/CaloMET/All/METTask_CaloMEx", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing Ex distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#mex_plots>more</a>)" },
{ 'path': "JetMET/MET/CaloMET/All/METTask_CaloMEy", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing Ey distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#mey_plots>more</a>)" }])

shiftjetmetcosmicslayout(dqmitems, "02 PF MET Plots (for cosmics)", [{ 'path': "JetMET/MET/PfMET/All/METTask_PfMET", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" },
{ 'path': "JetMET/MET/PfMET/All/METTask_PfMETPhi", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }],
[{ 'path': "JetMET/MET/PfMET/All/METTask_PfMEx", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing Ex distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#mex_plots>more</a>)" },
{ 'path': "JetMET/MET/PfMET/All/METTask_PfMEy", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing Ey distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#mey_plots>more</a>)" }])

shiftjetmetcosmicslayout(dqmitems, "03 TC MET Plots (for cosmics)", [{ 'path': "JetMET/MET/TcMET/All/METTask_MET", 'draw': { 'withref': 'yes' }, 'description': "The Track Corrected Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" },
{ 'path': "JetMET/MET/TcMET/All/METTask_METPhi", 'draw': { 'withref': 'yes' }, 'description': "The Track Corrected Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }],
[{ 'path': "JetMET/MET/TcMET/All/METTask_MEx", 'draw': { 'withref': 'yes' }, 'description': "The Track Corrected Missing Ex distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#mex_plots>more</a>)" },
{ 'path': "JetMET/MET/TcMET/All/METTask_MEy", 'draw': { 'withref': 'yes' }, 'description': "The Track Corrected Missing Ey distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#mey_plots>more</a>)" }])

def shiftjetmethighjetlayout(i, p, *rows): i["00 Shift/JetMET/Cosmics/HighPtJet/" + p] = DQMItem(layout=rows)

shiftjetmethighjetlayout(dqmitems, "00 AK5 Calo Jet Plots (for high threshold jet triggered events)", [{ 'path': "JetMET/Jet/CleanedAntiKtJets/Pt_Hi", 'draw': { 'withref': 'yes' }, 'description': "Distribution of Jet Pt for all cleaned jets (event primary vertex requirement, passing high threshold single jet trigger, the distribution should be fast falling with no spikes) (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_pt_plots>more</a>)" }],
[{ 'path': "JetMET/Jet/CleanedAntiKtJets/Eta_Hi", 'draw': { 'withref': 'yes' }, 'description': "Eta distribution for all jets.  Should be smooth and without spikes (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_summary_plots#jet_eta_plots>more</a>)" }])

shiftjetmethighjetlayout(dqmitems, "01 PF Jet Plots (for high threshold jet triggered events)", [{ 'path': "JetMET/Jet/PFJets/Pt_Hi", 'draw': { 'withref': 'yes' }, 'description': "Distribution of Jet Pt for all Particle Flow jets (event primary vertex requirement, passing high threshold single jet trigger, the distribution should be fast falling with no spikes) (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_pt_plots>more</a>)" }],
[{ 'path': "JetMET/Jet/PFJets/Eta_Hi", 'draw': { 'withref': 'yes' }, 'description': "Eta distribution for Particle Flow jets.  Should be smooth and without spikes (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_summary_plots#jet_eta_plots>more</a>)" }])

shiftjetmethighjetlayout(dqmitems, "02 Calo MET Plots (for high threshold jet triggered events)", [{ 'path': "JetMET/MET/CaloMET/BasicCleanup/HighPtJet/METTask_CaloMET", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" }],
[{ 'path': "JetMET/MET/CaloMET/BasicCleanup/HighPtJet/METTask_CaloMETPhi", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }])

shiftjetmethighjetlayout(dqmitems, "03 PF MET Plots (for high threshold jet triggered events)", [{ 'path': "JetMET/MET/PfMET/BasicCleanup/HighPtJet/METTask_PfMET", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" }],
[{ 'path': "JetMET/MET/PfMET/BasicCleanup/HighPtJet/METTask_PfMETPhi", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }])

shiftjetmethighjetlayout(dqmitems, "04 TC MET Plots (for high threshold jet triggered events)", [{ 'path': "JetMET/MET/TcMET/BasicCleanup/HighPtJet/METTask_MET", 'draw': { 'withref': 'yes' }, 'description': "The Track Corrected Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" }],
[{ 'path': "JetMET/MET/TcMET/BasicCleanup/HighPtJet/METTask_METPhi", 'draw': { 'withref': 'yes' }, 'description': "The Track Corrected Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }])

def shiftjetmetlowjetlayout(i, p, *rows): i["00 Shift/JetMET/Cosmics/LowPtJet/" + p] = DQMItem(layout=rows)

shiftjetmetlowjetlayout(dqmitems, "00 AK5 Calo Jet Plots (for low threshold jet triggered events)", [{ 'path': "JetMET/Jet/CleanedAntiKtJets/Pt_Lo", 'draw': { 'withref': 'yes' }, 'description': "Distribution of Jet Pt for all cleaned jets (event primary vertex requirement, passing low threshold single jet trigger, the distribution should be fast falling with no spikes) (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_pt_plots>more</a>)" }],
[{ 'path': "JetMET/Jet/CleanedAntiKtJets/Eta_Lo", 'draw': { 'withref': 'yes' }, 'description': "Eta distribution for all jets.  Should be smooth and without spikes (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_summary_plots#jet_eta_plots>more</a>)" }])

shiftjetmetlowjetlayout(dqmitems, "01 PF Jet Plots (for low threshold jet triggered events)", [{ 'path': "JetMET/Jet/PFJets/Pt_Lo", 'draw': { 'withref': 'yes' }, 'description': "Distribution of Jet Pt for all Particle Flow jets (event primary vertex requirement, passing low threshold single jet trigger, the distribution should be fast falling with no spikes) (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_pt_plots>more</a>)" }],
[{ 'path': "JetMET/Jet/PFJets/Eta_Lo", 'draw': { 'withref': 'yes' }, 'description': "Eta distribution for Particle Flow jets.  Should be smooth and without spikes (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#jet_summary_plots#jet_eta_plots>more</a>)" }])

shiftjetmetlowjetlayout(dqmitems, "02 Calo MET Plots (for low threshold jet triggered events)", [{ 'path': "JetMET/MET/CaloMET/BasicCleanup/LowPtJet/METTask_CaloMET", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" }],
[{ 'path': "JetMET/MET/CaloMET/BasicCleanup/LowPtJet/METTask_CaloMETPhi", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }])

shiftjetmetlowjetlayout(dqmitems, "03 PF MET Plots (for low threshold jet triggered events)", [{ 'path': "JetMET/MET/PfMET/BasicCleanup/LowPtJet/METTask_PfMET", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" }],
[{ 'path': "JetMET/MET/PfMET/BasicCleanup/LowPtJet/METTask_PfMETPhi", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }])

shiftjetmetlowjetlayout(dqmitems, "04 TC MET Plots (for low threshold jet triggered events)", [{ 'path': "JetMET/MET/TcMET/BasicCleanup/LowPtJet/METTask_MET", 'draw': { 'withref': 'yes' }, 'description': "The Track Corrected Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" }],
[{ 'path': "JetMET/MET/TcMET/BasicCleanup/LowPtJet/METTask_METPhi", 'draw': { 'withref': 'yes' }, 'description': "The Track Corrected Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }])

def shiftjetmethighmetlayout(i, p, *rows): i["00 Shift/JetMET/Cosmics/HighMET/" + p] = DQMItem(layout=rows)

shiftjetmethighmetlayout(dqmitems, "00 Calo MET Plots (for low threshold jet triggered events)", [{ 'path': "JetMET/MET/CaloMET/BasicCleanup/HighMET/METTask_CaloMET", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" }],
[{ 'path': "JetMET/MET/CaloMET/BasicCleanup/HighMET/METTask_CaloMETPhi", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }])

shiftjetmethighmetlayout(dqmitems, "01 PF MET Plots (for low threshold jet triggered events)", [{ 'path': "JetMET/MET/PfMET/BasicCleanup/HighMET/METTask_PfMET", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" }],
[{ 'path': "JetMET/MET/PfMET/BasicCleanup/HighMET/METTask_PfMETPhi", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }])

shiftjetmethighmetlayout(dqmitems, "02 TC MET Plots (for low threshold jet triggered events)", [{ 'path': "JetMET/MET/TcMET/BasicCleanup/HighMET/METTask_MET", 'draw': { 'withref': 'yes' }, 'description': "The Track Corrected Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" }],
[{ 'path': "JetMET/MET/TcMET/BasicCleanup/HighMET/METTask_METPhi", 'draw': { 'withref': 'yes' }, 'description': "The Track Corrected Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }])

def shiftjetmetlowmetlayout(i, p, *rows): i["00 Shift/JetMET/Cosmics/LowMET/" + p] = DQMItem(layout=rows)

shiftjetmetlowmetlayout(dqmitems, "00 Calo MET Plots (for low threshold jet triggered events)", [{ 'path': "JetMET/MET/CaloMET/BasicCleanup/LowMET/METTask_CaloMET", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" }],
[{ 'path': "JetMET/MET/CaloMET/BasicCleanup/LowMET/METTask_CaloMETPhi", 'draw': { 'withref': 'yes' }, 'description': "The Calorimeter Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }])

shiftjetmetlowmetlayout(dqmitems, "01 PF MET Plots (for low threshold jet triggered events)", [{ 'path': "JetMET/MET/PfMET/BasicCleanup/LowMET/METTask_PfMET", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" }],
[{ 'path': "JetMET/MET/PfMET/BasicCleanup/LowMET/METTask_PfMETPhi", 'draw': { 'withref': 'yes' }, 'description': "The Particle Flow Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }])

shiftjetmetlowmetlayout(dqmitems, "02 TC MET Plots (for low threshold jet triggered events)", [{ 'path': "JetMET/MET/TcMET/BasicCleanup/LowMET/METTask_MET", 'draw': { 'withref': 'yes' }, 'description': "The Track Corrected Missing ET distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_plots>more</a>)" }],
[{ 'path': "JetMET/MET/TcMET/BasicCleanup/LowMET/METTask_METPhi", 'draw': { 'withref': 'yes' }, 'description': "The Track Corrected Missing ET phi distribution.  There should not be any spikes in the distribution (<a href=https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftOfflineJetMET#met_phi_plots>more</a>)" }])
