if __name__=="__main__":
	class DQMItem:
		def __init__(self,layout):
			print layout
	dqmitems={}

def shifthcalcaliblayout(i, p, *rows): i['00 Shift/HcalCalib/' + p] = DQMItem(layout=rows)


shifthcalcaliblayout(dqmitems, '00 Current Summary', [{'path':'HcalCalib/PedestalTask/Summary/Summary', 'description':"""Calibration Summary. Anything that is not either WHITE or GREEN is BAD.<br>Color Scheme:<br><font color='green'>GOOD</font> for GOOD<br><font color='yellow'>PROBLEMATIC</font> for Problematic<br><font color='red'>BAD</font> for BAD<br><font color='black'>BAD</font> for BAD<br>WHITE color stands for INAPPLICABLE flag<br>Flags(Y) vs FED(X). For details...   <a href="https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Summary_Generation_Description">Details...</a>"""}])

shifthcalcaliblayout(dqmitems, '09 Pedestal Mean Bad', [{'path':'HcalCalib/PedestalTask/MeanBad/depth/depth1', 'description':"""Bad Pedestal Means w.r.t. CondDB.   <a href="https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description">Details...</a>"""}, {'path':'HcalCalib/PedestalTask/MeanBad/depth/depth2', 'description':"""Bad Pedestal Means w.r.t. CondDB.   <a href="https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description">Details...</a>"""}], [{'path':'HcalCalib/PedestalTask/MeanBad/depth/depth3', 'description':"""Bad Pedestal Means w.r.t. CondDB.   <a href="https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description">Details...</a>"""}, {'path':'HcalCalib/PedestalTask/MeanBad/depth/depth4', 'description':"""Bad Pedestal Means w.r.t. CondDB.   <a href="https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description">Details...</a>"""}])

shifthcalcaliblayout(dqmitems, '11 Pedestal RMS Bad', [{'path':'HcalCalib/PedestalTask/RMSBad/depth/depth1', 'description':"""Bad Pedestal RMS w.r.t. CondDB.   <a href="https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description">Details...</a>"""}, {'path':'HcalCalib/PedestalTask/RMSBad/depth/depth2', 'description':"""Bad Pedestal RMS w.r.t. CondDB.   <a href="https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description">Details...</a>"""}], [{'path':'HcalCalib/PedestalTask/RMSBad/depth/depth3', 'description':"""Bad Pedestal RMS w.r.t. CondDB.   <a href="https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description">Details...</a>"""}, {'path':'HcalCalib/PedestalTask/RMSBad/depth/depth4', 'description':"""Bad Pedestal RMS w.r.t. CondDB.   <a href="https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description">Details...</a>"""}])

shifthcalcaliblayout(dqmitems, '13 Pedestal Missing', [{'path':'HcalCalib/PedestalTask/Missing/depth/depth1', 'description':"""Missing channels w.r.t. CondDB.   <a href="https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Digi_Comparison_Task_VME_vs_uTCA">Details...</a>"""}, {'path':'HcalCalib/PedestalTask/Missing/depth/depth2', 'description':"""Missing channels w.r.t. CondDB.   <a href="https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Digi_Comparison_Task_VME_vs_uTCA">Details...</a>"""}], [{'path':'HcalCalib/PedestalTask/Missing/depth/depth3', 'description':"""Missing channels w.r.t. CondDB.   <a href="https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Digi_Comparison_Task_VME_vs_uTCA">Details...</a>"""}, {'path':'HcalCalib/PedestalTask/Missing/depth/depth4', 'description':"""Missing channels w.r.t. CondDB.   <a href="https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Digi_Comparison_Task_VME_vs_uTCA">Details...</a>"""}])
