if __name__=="__main__":
	class DQMItem:
		def __init__(self,layout):
			print layout
	dqmitems={}

def shifthcalcaliblayout(i, p, *rows): i['00 Shift/HcalCalib/' + p] = DQMItem(layout=rows)


shifthcalcaliblayout(dqmitems, '00 Run Summary', [{'path':'HcalCalib/PedestalTask/SummaryvsLS/SummaryvsLS', 'description':"""Calibration Summary. Anything that is not either WHITE or GREEN or Gray is BAD.<br> Color Scheme:<br><font color='green'>GOOD</font> for GOOD<br><font color='yellow'>PROBLEMATIC</font> for Problematic<br><font color='red'>BAD</font> for BAD<br><font color='black'>RESERVED</font> Not used at the moment <br><font color='gray'>NCDAQ with Gray Font</font> FED is excluded from cDAQ<br>WHITE color stands for INAPPLICABLE flag<br>FED(Y) vs LS(X). All the Monitoring Tasks are summarized. For details...  <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}, {'path':'HcalCalib/RawTask/SummaryvsLS/SummaryvsLS', 'description':"""RAW Summary Summary. Anything that is not either WHITE or GREEN or Gray is BAD.<br> Color Scheme:<br><font color='green'>GOOD</font> for GOOD<br><font color='yellow'>PROBLEMATIC</font> for Problematic<br><font color='red'>BAD</font> for BAD<br><font color='black'>RESERVED</font> Not used at the moment <br><font color='gray'>NCDAQ with Gray Font</font> FED is excluded from cDAQ<br>WHITE color stands for INAPPLICABLE flag<br>FED(Y) vs LS(X). All the Monitoring Tasks are summarized. For details...  <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Raw_Task_Description'>Details...</a>"""}])

shifthcalcaliblayout(dqmitems, '01 Pedestal Mean vs CondDB', [{'path':'HcalCalib/PedestalTask/MeanDBRef/Subdet/HB', 'description':"""Comparison of Pedestal Mean with CondBDStatistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}, {'path':'HcalCalib/PedestalTask/MeanDBRef/Subdet/HE', 'description':"""Comparison of Pedestal Mean with CondBDStatistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}], [{'path':'HcalCalib/PedestalTask/MeanDBRef/Subdet/HF', 'description':"""Comparison of Pedestal Mean with CondBDStatistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}, {'path':'HcalCalib/PedestalTask/MeanDBRef/Subdet/HO', 'description':"""Comparison of Pedestal Mean with CondBDStatistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}])

shifthcalcaliblayout(dqmitems, '02 Pedestal Mean vs CondDB', [{'path':'HcalCalib/PedestalTask/MeanDBRef/depth/depth1', 'description':"""Comparison of Pedestal Mean with CondBDStatistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}, {'path':'HcalCalib/PedestalTask/MeanDBRef/depth/depth2', 'description':"""Comparison of Pedestal Mean with CondBDStatistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}], [{'path':'HcalCalib/PedestalTask/MeanDBRef/depth/depth3', 'description':"""Comparison of Pedestal Mean with CondBDStatistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}, {'path':'HcalCalib/PedestalTask/MeanDBRef/depth/depth4', 'description':"""Comparison of Pedestal Mean with CondBDStatistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}])

shifthcalcaliblayout(dqmitems, '03 Pedestal RMS vs CondDB', [{'path':'HcalCalib/PedestalTask/RMSDBRef/Subdet/HB', 'description':"""Comparison of Pedestal RMS with the CondDB Statistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}, {'path':'HcalCalib/PedestalTask/RMSDBRef/Subdet/HE', 'description':"""Comparison of Pedestal RMS with the CondDB Statistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}], [{'path':'HcalCalib/PedestalTask/RMSDBRef/Subdet/HF', 'description':"""Comparison of Pedestal RMS with the CondDB Statistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}, {'path':'HcalCalib/PedestalTask/RMSDBRef/Subdet/HO', 'description':"""Comparison of Pedestal RMS with the CondDB Statistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}])

shifthcalcaliblayout(dqmitems, '04 Pedestal RMS vs CondDB', [{'path':'HcalCalib/PedestalTask/RMSDBRef/depth/depth1', 'description':"""Comparison of Pedestal RMS with the CondDB Statistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}, {'path':'HcalCalib/PedestalTask/RMSDBRef/depth/depth2', 'description':"""Comparison of Pedestal RMS with the CondDB Statistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}], [{'path':'HcalCalib/PedestalTask/RMSDBRef/depth/depth3', 'description':"""Comparison of Pedestal RMS with the CondDB Statistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}, {'path':'HcalCalib/PedestalTask/RMSDBRef/depth/depth4', 'description':"""Comparison of Pedestal RMS with the CondDB Statistics over the whole Run is combined. Either all LSs up to the current one or up to end of the Run <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}])

shifthcalcaliblayout(dqmitems, '05 Pedestal Missing vs LS', [{'path':'HcalCalib/PedestalTask/MissingvsLS/Subdet/HB', 'description':"""Missing channels vs LS <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}, {'path':'HcalCalib/PedestalTask/MissingvsLS/Subdet/HE', 'description':"""Missing channels vs LS <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}], [{'path':'HcalCalib/PedestalTask/MissingvsLS/Subdet/HF', 'description':"""Missing channels vs LS <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}, {'path':'HcalCalib/PedestalTask/MissingvsLS/Subdet/HO', 'description':"""Missing channels vs LS <a href='https://twiki.cern.ch/twiki/bin/view/CMS/HcalDQMRun2TaskDescription#Pedestal_Task_Description'>Details...</a>"""}])
